// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: machine/proto/definition.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	MinDiskMb     int32                  `protobuf:"varint,3,opt,name=min_disk_mb,json=minDiskMb,proto3" json:"min_disk_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineConfig) Reset() {
	*x = MachineConfig{}
	mi := &file_machine_proto_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineConfig) ProtoMessage() {}

func (x *MachineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineConfig.ProtoReflect.Descriptor instead.
func (*MachineConfig) Descriptor() ([]byte, []int) {
	return file_machine_proto_definition_proto_rawDescGZIP(), []int{0}
}

func (x *MachineConfig) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *MachineConfig) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *MachineConfig) GetMinDiskMb() int32 {
	if x != nil {
		return x.MinDiskMb
	}
	return 0
}

type CreateMachineDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directives    []*Directive           `protobuf:"bytes,1,rep,name=directives,proto3" json:"directives,omitempty"`
	Config        *MachineConfig         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMachineDefinition) Reset() {
	*x = CreateMachineDefinition{}
	mi := &file_machine_proto_definition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMachineDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMachineDefinition) ProtoMessage() {}

func (x *CreateMachineDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_definition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMachineDefinition.ProtoReflect.Descriptor instead.
func (*CreateMachineDefinition) Descriptor() ([]byte, []int) {
	return file_machine_proto_definition_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMachineDefinition) GetDirectives() []*Directive {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *CreateMachineDefinition) GetConfig() *MachineConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_machine_proto_definition_proto protoreflect.FileDescriptor

const file_machine_proto_definition_proto_rawDesc = "" +
	"\n" +
	"\x1emachine/proto/definition.proto\x12\x05proto\x1a\x1dmachine/proto/directive.proto\"i\n" +
	"\rMachineConfig\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x05R\bmemoryMb\x12\x1e\n" +
	"\vmin_disk_mb\x18\x03 \x01(\x05R\tminDiskMb\"y\n" +
	"\x17CreateMachineDefinition\x120\n" +
	"\n" +
	"directives\x18\x01 \x03(\v2\x10.proto.DirectiveR\n" +
	"directives\x12,\n" +
	"\x06config\x18\x02 \x01(\v2\x14.proto.MachineConfigR\x06configB.Z,github.com/tinyrange/tinyrange/machine/protob\x06proto3"

var (
	file_machine_proto_definition_proto_rawDescOnce sync.Once
	file_machine_proto_definition_proto_rawDescData []byte
)

func file_machine_proto_definition_proto_rawDescGZIP() []byte {
	file_machine_proto_definition_proto_rawDescOnce.Do(func() {
		file_machine_proto_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_machine_proto_definition_proto_rawDesc), len(file_machine_proto_definition_proto_rawDesc)))
	})
	return file_machine_proto_definition_proto_rawDescData
}

var file_machine_proto_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_machine_proto_definition_proto_goTypes = []any{
	(*MachineConfig)(nil),           // 0: proto.MachineConfig
	(*CreateMachineDefinition)(nil), // 1: proto.CreateMachineDefinition
	(*Directive)(nil),               // 2: proto.Directive
}
var file_machine_proto_definition_proto_depIdxs = []int32{
	2, // 0: proto.CreateMachineDefinition.directives:type_name -> proto.Directive
	0, // 1: proto.CreateMachineDefinition.config:type_name -> proto.MachineConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_machine_proto_definition_proto_init() }
func file_machine_proto_definition_proto_init() {
	if File_machine_proto_definition_proto != nil {
		return
	}
	file_machine_proto_directive_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_machine_proto_definition_proto_rawDesc), len(file_machine_proto_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_machine_proto_definition_proto_goTypes,
		DependencyIndexes: file_machine_proto_definition_proto_depIdxs,
		MessageInfos:      file_machine_proto_definition_proto_msgTypes,
	}.Build()
	File_machine_proto_definition_proto = out.File
	file_machine_proto_definition_proto_goTypes = nil
	file_machine_proto_definition_proto_depIdxs = nil
}
