// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: machine/proto/directive.proto

package proto

import (
	proto "github.com/tinyrange/tinyrange/build/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunCommandDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandDirective) Reset() {
	*x = RunCommandDirective{}
	mi := &file_machine_proto_directive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandDirective) ProtoMessage() {}

func (x *RunCommandDirective) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_directive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandDirective.ProtoReflect.Descriptor instead.
func (*RunCommandDirective) Descriptor() ([]byte, []int) {
	return file_machine_proto_directive_proto_rawDescGZIP(), []int{0}
}

func (x *RunCommandDirective) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type EnvironmentDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variables     map[string]string      `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentDirective) Reset() {
	*x = EnvironmentDirective{}
	mi := &file_machine_proto_directive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentDirective) ProtoMessage() {}

func (x *EnvironmentDirective) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_directive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentDirective.ProtoReflect.Descriptor instead.
func (*EnvironmentDirective) Descriptor() ([]byte, []int) {
	return file_machine_proto_directive_proto_rawDescGZIP(), []int{1}
}

func (x *EnvironmentDirective) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type ExportPortDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPortDirective) Reset() {
	*x = ExportPortDirective{}
	mi := &file_machine_proto_directive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPortDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPortDirective) ProtoMessage() {}

func (x *ExportPortDirective) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_directive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPortDirective.ProtoReflect.Descriptor instead.
func (*ExportPortDirective) Descriptor() ([]byte, []int) {
	return file_machine_proto_directive_proto_rawDescGZIP(), []int{2}
}

func (x *ExportPortDirective) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type FileContents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Contents:
	//
	//	*FileContents_Raw
	Contents      isFileContents_Contents `protobuf_oneof:"contents"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContents) Reset() {
	*x = FileContents{}
	mi := &file_machine_proto_directive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContents) ProtoMessage() {}

func (x *FileContents) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_directive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContents.ProtoReflect.Descriptor instead.
func (*FileContents) Descriptor() ([]byte, []int) {
	return file_machine_proto_directive_proto_rawDescGZIP(), []int{3}
}

func (x *FileContents) GetContents() isFileContents_Contents {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *FileContents) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Contents.(*FileContents_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isFileContents_Contents interface {
	isFileContents_Contents()
}

type FileContents_Raw struct {
	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3,oneof"`
}

func (*FileContents_Raw) isFileContents_Contents() {}

type AddFileDirective struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*AddFileDirective_Src
	//	*AddFileDirective_Contents
	Source        isAddFileDirective_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFileDirective) Reset() {
	*x = AddFileDirective{}
	mi := &file_machine_proto_directive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFileDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFileDirective) ProtoMessage() {}

func (x *AddFileDirective) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_directive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFileDirective.ProtoReflect.Descriptor instead.
func (*AddFileDirective) Descriptor() ([]byte, []int) {
	return file_machine_proto_directive_proto_rawDescGZIP(), []int{4}
}

func (x *AddFileDirective) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddFileDirective) GetSource() isAddFileDirective_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *AddFileDirective) GetSrc() *proto.FileSource {
	if x != nil {
		if x, ok := x.Source.(*AddFileDirective_Src); ok {
			return x.Src
		}
	}
	return nil
}

func (x *AddFileDirective) GetContents() *FileContents {
	if x != nil {
		if x, ok := x.Source.(*AddFileDirective_Contents); ok {
			return x.Contents
		}
	}
	return nil
}

type isAddFileDirective_Source interface {
	isAddFileDirective_Source()
}

type AddFileDirective_Src struct {
	Src *proto.FileSource `protobuf:"bytes,2,opt,name=src,proto3,oneof"`
}

type AddFileDirective_Contents struct {
	Contents *FileContents `protobuf:"bytes,3,opt,name=contents,proto3,oneof"`
}

func (*AddFileDirective_Src) isAddFileDirective_Source() {}

func (*AddFileDirective_Contents) isAddFileDirective_Source() {}

type AddArchiveDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Source        *proto.FileSource      `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArchiveDirective) Reset() {
	*x = AddArchiveDirective{}
	mi := &file_machine_proto_directive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArchiveDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArchiveDirective) ProtoMessage() {}

func (x *AddArchiveDirective) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_directive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArchiveDirective.ProtoReflect.Descriptor instead.
func (*AddArchiveDirective) Descriptor() ([]byte, []int) {
	return file_machine_proto_directive_proto_rawDescGZIP(), []int{5}
}

func (x *AddArchiveDirective) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AddArchiveDirective) GetSource() *proto.FileSource {
	if x != nil {
		return x.Source
	}
	return nil
}

type AddVolumeDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MountPath     string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	SizeMb        int32                  `protobuf:"varint,3,opt,name=size_mb,json=sizeMb,proto3" json:"size_mb,omitempty"`
	Persistent    bool                   `protobuf:"varint,4,opt,name=persistent,proto3" json:"persistent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVolumeDirective) Reset() {
	*x = AddVolumeDirective{}
	mi := &file_machine_proto_directive_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVolumeDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVolumeDirective) ProtoMessage() {}

func (x *AddVolumeDirective) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_directive_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVolumeDirective.ProtoReflect.Descriptor instead.
func (*AddVolumeDirective) Descriptor() ([]byte, []int) {
	return file_machine_proto_directive_proto_rawDescGZIP(), []int{6}
}

func (x *AddVolumeDirective) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddVolumeDirective) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *AddVolumeDirective) GetSizeMb() int32 {
	if x != nil {
		return x.SizeMb
	}
	return 0
}

func (x *AddVolumeDirective) GetPersistent() bool {
	if x != nil {
		return x.Persistent
	}
	return false
}

type Directive struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Directive:
	//
	//	*Directive_AddFile
	//	*Directive_Archive
	//	*Directive_RunCommand
	//	*Directive_Environment
	//	*Directive_ExportPort
	//	*Directive_Volume
	Directive     isDirective_Directive `protobuf_oneof:"directive"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directive) Reset() {
	*x = Directive{}
	mi := &file_machine_proto_directive_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directive) ProtoMessage() {}

func (x *Directive) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_directive_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directive.ProtoReflect.Descriptor instead.
func (*Directive) Descriptor() ([]byte, []int) {
	return file_machine_proto_directive_proto_rawDescGZIP(), []int{7}
}

func (x *Directive) GetDirective() isDirective_Directive {
	if x != nil {
		return x.Directive
	}
	return nil
}

func (x *Directive) GetAddFile() *AddFileDirective {
	if x != nil {
		if x, ok := x.Directive.(*Directive_AddFile); ok {
			return x.AddFile
		}
	}
	return nil
}

func (x *Directive) GetArchive() *AddArchiveDirective {
	if x != nil {
		if x, ok := x.Directive.(*Directive_Archive); ok {
			return x.Archive
		}
	}
	return nil
}

func (x *Directive) GetRunCommand() *RunCommandDirective {
	if x != nil {
		if x, ok := x.Directive.(*Directive_RunCommand); ok {
			return x.RunCommand
		}
	}
	return nil
}

func (x *Directive) GetEnvironment() *EnvironmentDirective {
	if x != nil {
		if x, ok := x.Directive.(*Directive_Environment); ok {
			return x.Environment
		}
	}
	return nil
}

func (x *Directive) GetExportPort() *ExportPortDirective {
	if x != nil {
		if x, ok := x.Directive.(*Directive_ExportPort); ok {
			return x.ExportPort
		}
	}
	return nil
}

func (x *Directive) GetVolume() *AddVolumeDirective {
	if x != nil {
		if x, ok := x.Directive.(*Directive_Volume); ok {
			return x.Volume
		}
	}
	return nil
}

type isDirective_Directive interface {
	isDirective_Directive()
}

type Directive_AddFile struct {
	// Basic filesystem manipulation
	AddFile *AddFileDirective `protobuf:"bytes,1,opt,name=add_file,json=addFile,proto3,oneof"`
}

type Directive_Archive struct {
	Archive *AddArchiveDirective `protobuf:"bytes,2,opt,name=archive,proto3,oneof"`
}

type Directive_RunCommand struct {
	// Machine configuration
	RunCommand *RunCommandDirective `protobuf:"bytes,3,opt,name=run_command,json=runCommand,proto3,oneof"`
}

type Directive_Environment struct {
	Environment *EnvironmentDirective `protobuf:"bytes,4,opt,name=environment,proto3,oneof"`
}

type Directive_ExportPort struct {
	ExportPort *ExportPortDirective `protobuf:"bytes,5,opt,name=export_port,json=exportPort,proto3,oneof"`
}

type Directive_Volume struct {
	Volume *AddVolumeDirective `protobuf:"bytes,6,opt,name=volume,proto3,oneof"`
}

func (*Directive_AddFile) isDirective_Directive() {}

func (*Directive_Archive) isDirective_Directive() {}

func (*Directive_RunCommand) isDirective_Directive() {}

func (*Directive_Environment) isDirective_Directive() {}

func (*Directive_ExportPort) isDirective_Directive() {}

func (*Directive_Volume) isDirective_Directive() {}

var File_machine_proto_directive_proto protoreflect.FileDescriptor

const file_machine_proto_directive_proto_rawDesc = "" +
	"\n" +
	"\x1dmachine/proto/directive.proto\x12\x05proto\x1a\x18build/proto/source.proto\"/\n" +
	"\x13RunCommandDirective\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"\x9e\x01\n" +
	"\x14EnvironmentDirective\x12H\n" +
	"\tvariables\x18\x01 \x03(\v2*.proto.EnvironmentDirective.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x13ExportPortDirective\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\".\n" +
	"\fFileContents\x12\x12\n" +
	"\x03raw\x18\x01 \x01(\fH\x00R\x03rawB\n" +
	"\n" +
	"\bcontents\"\x8a\x01\n" +
	"\x10AddFileDirective\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12%\n" +
	"\x03src\x18\x02 \x01(\v2\x11.proto.FileSourceH\x00R\x03src\x121\n" +
	"\bcontents\x18\x03 \x01(\v2\x13.proto.FileContentsH\x00R\bcontentsB\b\n" +
	"\x06source\"X\n" +
	"\x13AddArchiveDirective\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12)\n" +
	"\x06source\x18\x02 \x01(\v2\x11.proto.FileSourceR\x06source\"\x80\x01\n" +
	"\x12AddVolumeDirective\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\x12\x17\n" +
	"\asize_mb\x18\x03 \x01(\x05R\x06sizeMb\x12\x1e\n" +
	"\n" +
	"persistent\x18\x04 \x01(\bR\n" +
	"persistent\"\xfa\x02\n" +
	"\tDirective\x124\n" +
	"\badd_file\x18\x01 \x01(\v2\x17.proto.AddFileDirectiveH\x00R\aaddFile\x126\n" +
	"\aarchive\x18\x02 \x01(\v2\x1a.proto.AddArchiveDirectiveH\x00R\aarchive\x12=\n" +
	"\vrun_command\x18\x03 \x01(\v2\x1a.proto.RunCommandDirectiveH\x00R\n" +
	"runCommand\x12?\n" +
	"\venvironment\x18\x04 \x01(\v2\x1b.proto.EnvironmentDirectiveH\x00R\venvironment\x12=\n" +
	"\vexport_port\x18\x05 \x01(\v2\x1a.proto.ExportPortDirectiveH\x00R\n" +
	"exportPort\x123\n" +
	"\x06volume\x18\x06 \x01(\v2\x19.proto.AddVolumeDirectiveH\x00R\x06volumeB\v\n" +
	"\tdirectiveB.Z,github.com/tinyrange/tinyrange/machine/protob\x06proto3"

var (
	file_machine_proto_directive_proto_rawDescOnce sync.Once
	file_machine_proto_directive_proto_rawDescData []byte
)

func file_machine_proto_directive_proto_rawDescGZIP() []byte {
	file_machine_proto_directive_proto_rawDescOnce.Do(func() {
		file_machine_proto_directive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_machine_proto_directive_proto_rawDesc), len(file_machine_proto_directive_proto_rawDesc)))
	})
	return file_machine_proto_directive_proto_rawDescData
}

var file_machine_proto_directive_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_machine_proto_directive_proto_goTypes = []any{
	(*RunCommandDirective)(nil),  // 0: proto.RunCommandDirective
	(*EnvironmentDirective)(nil), // 1: proto.EnvironmentDirective
	(*ExportPortDirective)(nil),  // 2: proto.ExportPortDirective
	(*FileContents)(nil),         // 3: proto.FileContents
	(*AddFileDirective)(nil),     // 4: proto.AddFileDirective
	(*AddArchiveDirective)(nil),  // 5: proto.AddArchiveDirective
	(*AddVolumeDirective)(nil),   // 6: proto.AddVolumeDirective
	(*Directive)(nil),            // 7: proto.Directive
	nil,                          // 8: proto.EnvironmentDirective.VariablesEntry
	(*proto.FileSource)(nil),     // 9: proto.FileSource
}
var file_machine_proto_directive_proto_depIdxs = []int32{
	8,  // 0: proto.EnvironmentDirective.variables:type_name -> proto.EnvironmentDirective.VariablesEntry
	9,  // 1: proto.AddFileDirective.src:type_name -> proto.FileSource
	3,  // 2: proto.AddFileDirective.contents:type_name -> proto.FileContents
	9,  // 3: proto.AddArchiveDirective.source:type_name -> proto.FileSource
	4,  // 4: proto.Directive.add_file:type_name -> proto.AddFileDirective
	5,  // 5: proto.Directive.archive:type_name -> proto.AddArchiveDirective
	0,  // 6: proto.Directive.run_command:type_name -> proto.RunCommandDirective
	1,  // 7: proto.Directive.environment:type_name -> proto.EnvironmentDirective
	2,  // 8: proto.Directive.export_port:type_name -> proto.ExportPortDirective
	6,  // 9: proto.Directive.volume:type_name -> proto.AddVolumeDirective
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_machine_proto_directive_proto_init() }
func file_machine_proto_directive_proto_init() {
	if File_machine_proto_directive_proto != nil {
		return
	}
	file_machine_proto_directive_proto_msgTypes[3].OneofWrappers = []any{
		(*FileContents_Raw)(nil),
	}
	file_machine_proto_directive_proto_msgTypes[4].OneofWrappers = []any{
		(*AddFileDirective_Src)(nil),
		(*AddFileDirective_Contents)(nil),
	}
	file_machine_proto_directive_proto_msgTypes[7].OneofWrappers = []any{
		(*Directive_AddFile)(nil),
		(*Directive_Archive)(nil),
		(*Directive_RunCommand)(nil),
		(*Directive_Environment)(nil),
		(*Directive_ExportPort)(nil),
		(*Directive_Volume)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_machine_proto_directive_proto_rawDesc), len(file_machine_proto_directive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_machine_proto_directive_proto_goTypes,
		DependencyIndexes: file_machine_proto_directive_proto_depIdxs,
		MessageInfos:      file_machine_proto_directive_proto_msgTypes,
	}.Build()
	File_machine_proto_directive_proto = out.File
	file_machine_proto_directive_proto_goTypes = nil
	file_machine_proto_directive_proto_depIdxs = nil
}
