#!/usr/bin/env tinyrange

version: 1
architecture: x86_64
builder: alpine@3.21
environment:
  - KERNEL_VERSION=4.19.28
commands:
  - mv /root/linux-$KERNEL_VERSION.proposed.config /root/linux-$KERNEL_VERSION/.config
  - cd /root/linux-$KERNEL_VERSION; make -j6
  - mv /root/linux-$KERNEL_VERSION/arch/x86/boot/bzImage /root/vmlinux-$KERNEL_VERSION.proposed
files:
  - linux-$KERNEL_VERSION.proposed.config
archives:
  - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-$KERNEL_VERSION.tar.xz
output: /root/vmlinux-$KERNEL_VERSION.proposed
packages:
  - build-base
  - flex
  - bison
  - gmp-dev
  - mpc1-dev
  - openssl-dev
  - linux-headers
  - elfutils-dev
  - findutils
  - diffutils
  - perl
min_spec:
  cpu: 6
  memory: 10240
  disk: 10240
