// generated by structGen. DO NOT EDIT MANUALLY

package main

import (
	"encoding/binary"
	"io"
	"fmt"
)

type MediaDescriptorType uint8

func (e MediaDescriptorType) String() string {
	switch e {
	default:
		return fmt.Sprintf("unknown <%d>", e)
	}
}
func (r Fat12And16ExtendedRecord) DriveNumberSlice() [1]byte {
	return [1]byte(r[0:1])
}
func (r Fat12And16ExtendedRecord) GetDriveNumber() uint8 {
	return uint8(r[0:1][0])
}
func (r *Fat12And16ExtendedRecord) SetDriveNumber(value uint8) {
	r[0:1][0] = byte(value)
}
func (r Fat12And16ExtendedRecord) NtFlagsSlice() [1]byte {
	return [1]byte(r[1:2])
}
func (r Fat12And16ExtendedRecord) GetNtFlags() uint8 {
	return uint8(r[1:2][0])
}
func (r *Fat12And16ExtendedRecord) SetNtFlags(value uint8) {
	r[1:2][0] = byte(value)
}
func (r Fat12And16ExtendedRecord) SignatureSlice() [1]byte {
	return [1]byte(r[2:3])
}
func (r Fat12And16ExtendedRecord) GetSignature() uint8 {
	return uint8(r[2:3][0])
}
func (r *Fat12And16ExtendedRecord) SetSignature(value uint8) {
	r[2:3][0] = byte(value)
}
func (r Fat12And16ExtendedRecord) VolumeIdSlice() [4]byte {
	return [4]byte(r[3:7])
}
func (r Fat12And16ExtendedRecord) GetVolumeId() uint32 {
	return binary.LittleEndian.Uint32(r[3:7])
}
func (r *Fat12And16ExtendedRecord) SetVolumeId(value uint32) {
	binary.LittleEndian.PutUint32(r[3:7], value)
}
func (r Fat12And16ExtendedRecord) VolumeLabelSlice() [11]byte {
	return [11]byte(r[7:18])
}
func (r Fat12And16ExtendedRecord) GetVolumeLabel() [11]byte {
	return [11]byte(r[7:18])
}
func (r *Fat12And16ExtendedRecord) SetVolumeLabel(value [11]byte) {
	copy(r[7:18], value[:])
}
func (r Fat12And16ExtendedRecord) SystemIdentifierSlice() [8]byte {
	return [8]byte(r[18:26])
}
func (r Fat12And16ExtendedRecord) GetSystemIdentifier() [8]byte {
	return [8]byte(r[18:26])
}
func (r *Fat12And16ExtendedRecord) SetSystemIdentifier(value [8]byte) {
	copy(r[18:26], value[:])
}
func (r Fat12And16ExtendedRecord) BootCodeSlice() [448]byte {
	return [448]byte(r[26:474])
}
func (r Fat12And16ExtendedRecord) GetBootCode() [448]uint8 {
	return [448]uint8(r[26:474])
}
func (r *Fat12And16ExtendedRecord) SetBootCode(value [448]uint8) {
	copy(r[26:474], value[:])
}
func (r Fat12And16ExtendedRecord) Size() int64 {
	return 474
}
func (r Fat12And16ExtendedRecord) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *Fat12And16ExtendedRecord) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type Fat12And16ExtendedRecord [474]byte

func (r Fat32ExtendedRecord) TableSize32Slice() [4]byte {
	return [4]byte(r[0:4])
}
func (r Fat32ExtendedRecord) GetTableSize32() uint32 {
	return binary.LittleEndian.Uint32(r[0:4])
}
func (r *Fat32ExtendedRecord) SetTableSize32(value uint32) {
	binary.LittleEndian.PutUint32(r[0:4], value)
}
func (r Fat32ExtendedRecord) FlagsSlice() [2]byte {
	return [2]byte(r[4:6])
}
func (r Fat32ExtendedRecord) GetFlags() uint16 {
	return binary.LittleEndian.Uint16(r[4:6])
}
func (r *Fat32ExtendedRecord) SetFlags(value uint16) {
	binary.LittleEndian.PutUint16(r[4:6], value)
}
func (r Fat32ExtendedRecord) VersionSlice() [2]byte {
	return [2]byte(r[6:8])
}
func (r Fat32ExtendedRecord) GetVersion() uint16 {
	return binary.LittleEndian.Uint16(r[6:8])
}
func (r *Fat32ExtendedRecord) SetVersion(value uint16) {
	binary.LittleEndian.PutUint16(r[6:8], value)
}
func (r Fat32ExtendedRecord) RootDirectoryClusterSlice() [4]byte {
	return [4]byte(r[8:12])
}
func (r Fat32ExtendedRecord) GetRootDirectoryCluster() uint32 {
	return binary.LittleEndian.Uint32(r[8:12])
}
func (r *Fat32ExtendedRecord) SetRootDirectoryCluster(value uint32) {
	binary.LittleEndian.PutUint32(r[8:12], value)
}
func (r Fat32ExtendedRecord) FsInfoSectorSlice() [2]byte {
	return [2]byte(r[12:14])
}
func (r Fat32ExtendedRecord) GetFsInfoSector() uint16 {
	return binary.LittleEndian.Uint16(r[12:14])
}
func (r *Fat32ExtendedRecord) SetFsInfoSector(value uint16) {
	binary.LittleEndian.PutUint16(r[12:14], value)
}
func (r Fat32ExtendedRecord) BackupBootSlice() [2]byte {
	return [2]byte(r[14:16])
}
func (r Fat32ExtendedRecord) GetBackupBoot() uint16 {
	return binary.LittleEndian.Uint16(r[14:16])
}
func (r *Fat32ExtendedRecord) SetBackupBoot(value uint16) {
	binary.LittleEndian.PutUint16(r[14:16], value)
}
func (r Fat32ExtendedRecord) DriveNumberSlice() [1]byte {
	return [1]byte(r[28:29])
}
func (r Fat32ExtendedRecord) GetDriveNumber() uint8 {
	return uint8(r[28:29][0])
}
func (r *Fat32ExtendedRecord) SetDriveNumber(value uint8) {
	r[28:29][0] = byte(value)
}
func (r Fat32ExtendedRecord) NtFlagsSlice() [1]byte {
	return [1]byte(r[29:30])
}
func (r Fat32ExtendedRecord) GetNtFlags() uint8 {
	return uint8(r[29:30][0])
}
func (r *Fat32ExtendedRecord) SetNtFlags(value uint8) {
	r[29:30][0] = byte(value)
}
func (r Fat32ExtendedRecord) SignatureSlice() [1]byte {
	return [1]byte(r[30:31])
}
func (r Fat32ExtendedRecord) GetSignature() uint8 {
	return uint8(r[30:31][0])
}
func (r *Fat32ExtendedRecord) SetSignature(value uint8) {
	r[30:31][0] = byte(value)
}
func (r Fat32ExtendedRecord) VolumeIdSlice() [4]byte {
	return [4]byte(r[31:35])
}
func (r Fat32ExtendedRecord) GetVolumeId() uint32 {
	return binary.LittleEndian.Uint32(r[31:35])
}
func (r *Fat32ExtendedRecord) SetVolumeId(value uint32) {
	binary.LittleEndian.PutUint32(r[31:35], value)
}
func (r Fat32ExtendedRecord) VolumeLabelSlice() [11]byte {
	return [11]byte(r[35:46])
}
func (r Fat32ExtendedRecord) GetVolumeLabel() [11]byte {
	return [11]byte(r[35:46])
}
func (r *Fat32ExtendedRecord) SetVolumeLabel(value [11]byte) {
	copy(r[35:46], value[:])
}
func (r Fat32ExtendedRecord) SystemIdentifierSlice() [8]byte {
	return [8]byte(r[46:54])
}
func (r Fat32ExtendedRecord) GetSystemIdentifier() [8]byte {
	return [8]byte(r[46:54])
}
func (r *Fat32ExtendedRecord) SetSystemIdentifier(value [8]byte) {
	copy(r[46:54], value[:])
}
func (r Fat32ExtendedRecord) BootCodeSlice() [420]byte {
	return [420]byte(r[54:474])
}
func (r Fat32ExtendedRecord) GetBootCode() [420]uint8 {
	return [420]uint8(r[54:474])
}
func (r *Fat32ExtendedRecord) SetBootCode(value [420]uint8) {
	copy(r[54:474], value[:])
}
func (r Fat32ExtendedRecord) Size() int64 {
	return 474
}
func (r Fat32ExtendedRecord) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *Fat32ExtendedRecord) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type Fat32ExtendedRecord [474]byte

func (u ExtendedBootRecord) GetRaw() [512 - 2 - 36]uint8 {
	return [512 - 2 - 36]uint8(u[:])
}
func (u ExtendedBootRecord) SetRaw(value [512 - 2 - 36]uint8) {
	copy(u[:], value[:])
}
func (u ExtendedBootRecord) GetFat12And16() Fat12And16ExtendedRecord {
	return Fat12And16ExtendedRecord(u[:])
}
func (u ExtendedBootRecord) SetFat12And16(value Fat12And16ExtendedRecord) {
	copy(u[:], value[:])
}
func (u ExtendedBootRecord) GetFat32() Fat32ExtendedRecord {
	return Fat32ExtendedRecord(u[:])
}
func (u ExtendedBootRecord) SetFat32(value Fat32ExtendedRecord) {
	copy(u[:], value[:])
}

type ExtendedBootRecord [474]byte

func (r BiosParameterBlock) JmpSlice() [3]byte {
	return [3]byte(r[0:3])
}
func (r BiosParameterBlock) GetJmp() [3]uint8 {
	return [3]uint8(r[0:3])
}
func (r *BiosParameterBlock) SetJmp(value [3]uint8) {
	copy(r[0:3], value[:])
}
func (r BiosParameterBlock) OemIdentifierSlice() [8]byte {
	return [8]byte(r[3:11])
}
func (r BiosParameterBlock) GetOemIdentifier() [8]byte {
	return [8]byte(r[3:11])
}
func (r *BiosParameterBlock) SetOemIdentifier(value [8]byte) {
	copy(r[3:11], value[:])
}
func (r BiosParameterBlock) BytesPerSectorSlice() [2]byte {
	return [2]byte(r[11:13])
}
func (r BiosParameterBlock) GetBytesPerSector() uint16 {
	return binary.LittleEndian.Uint16(r[11:13])
}
func (r *BiosParameterBlock) SetBytesPerSector(value uint16) {
	binary.LittleEndian.PutUint16(r[11:13], value)
}
func (r BiosParameterBlock) SectorsPerClusterSlice() [1]byte {
	return [1]byte(r[13:14])
}
func (r BiosParameterBlock) GetSectorsPerCluster() uint8 {
	return uint8(r[13:14][0])
}
func (r *BiosParameterBlock) SetSectorsPerCluster(value uint8) {
	r[13:14][0] = byte(value)
}
func (r BiosParameterBlock) ReservedSectorsSlice() [2]byte {
	return [2]byte(r[14:16])
}
func (r BiosParameterBlock) GetReservedSectors() uint16 {
	return binary.LittleEndian.Uint16(r[14:16])
}
func (r *BiosParameterBlock) SetReservedSectors(value uint16) {
	binary.LittleEndian.PutUint16(r[14:16], value)
}
func (r BiosParameterBlock) TableCountSlice() [1]byte {
	return [1]byte(r[16:17])
}
func (r BiosParameterBlock) GetTableCount() uint8 {
	return uint8(r[16:17][0])
}
func (r *BiosParameterBlock) SetTableCount(value uint8) {
	r[16:17][0] = byte(value)
}
func (r BiosParameterBlock) RootDirectoryEntriesSlice() [2]byte {
	return [2]byte(r[17:19])
}
func (r BiosParameterBlock) GetRootDirectoryEntries() uint16 {
	return binary.LittleEndian.Uint16(r[17:19])
}
func (r *BiosParameterBlock) SetRootDirectoryEntries(value uint16) {
	binary.LittleEndian.PutUint16(r[17:19], value)
}
func (r BiosParameterBlock) TotalSectors16Slice() [2]byte {
	return [2]byte(r[19:21])
}
func (r BiosParameterBlock) GetTotalSectors16() uint16 {
	return binary.LittleEndian.Uint16(r[19:21])
}
func (r *BiosParameterBlock) SetTotalSectors16(value uint16) {
	binary.LittleEndian.PutUint16(r[19:21], value)
}
func (r BiosParameterBlock) MediaDescriptorTypeSlice() [1]byte {
	return [1]byte(r[21:22])
}
func (r BiosParameterBlock) GetMediaDescriptorType() MediaDescriptorType {
	return MediaDescriptorType(r[21:22][0])
}
func (r *BiosParameterBlock) SetMediaDescriptorType(value MediaDescriptorType) {
	r[21:22][0] = byte(value)
}
func (r BiosParameterBlock) TableSize16Slice() [2]byte {
	return [2]byte(r[22:24])
}
func (r BiosParameterBlock) GetTableSize16() uint16 {
	return binary.LittleEndian.Uint16(r[22:24])
}
func (r *BiosParameterBlock) SetTableSize16(value uint16) {
	binary.LittleEndian.PutUint16(r[22:24], value)
}
func (r BiosParameterBlock) SectorsPerTrackSlice() [2]byte {
	return [2]byte(r[24:26])
}
func (r BiosParameterBlock) GetSectorsPerTrack() uint16 {
	return binary.LittleEndian.Uint16(r[24:26])
}
func (r *BiosParameterBlock) SetSectorsPerTrack(value uint16) {
	binary.LittleEndian.PutUint16(r[24:26], value)
}
func (r BiosParameterBlock) MediaHeadsSlice() [2]byte {
	return [2]byte(r[26:28])
}
func (r BiosParameterBlock) GetMediaHeads() uint16 {
	return binary.LittleEndian.Uint16(r[26:28])
}
func (r *BiosParameterBlock) SetMediaHeads(value uint16) {
	binary.LittleEndian.PutUint16(r[26:28], value)
}
func (r BiosParameterBlock) HiddenSectorsSlice() [4]byte {
	return [4]byte(r[28:32])
}
func (r BiosParameterBlock) GetHiddenSectors() uint32 {
	return binary.LittleEndian.Uint32(r[28:32])
}
func (r *BiosParameterBlock) SetHiddenSectors(value uint32) {
	binary.LittleEndian.PutUint32(r[28:32], value)
}
func (r BiosParameterBlock) TotalSectors32Slice() [4]byte {
	return [4]byte(r[32:36])
}
func (r BiosParameterBlock) GetTotalSectors32() uint32 {
	return binary.LittleEndian.Uint32(r[32:36])
}
func (r *BiosParameterBlock) SetTotalSectors32(value uint32) {
	binary.LittleEndian.PutUint32(r[32:36], value)
}
func (r BiosParameterBlock) ExtendedBootRecordSlice() [474]byte {
	return [474]byte(r[36:510])
}
func (r BiosParameterBlock) GetExtendedBootRecord() ExtendedBootRecord {
	return ExtendedBootRecord(r[36:510])
}
func (r *BiosParameterBlock) SetExtendedBootRecord(value ExtendedBootRecord) {
	copy(r[36:510], value[:])
}
func (r BiosParameterBlock) SignatureSlice() [2]byte {
	return [2]byte(r[510:512])
}
func (r BiosParameterBlock) GetSignature() uint16 {
	return binary.LittleEndian.Uint16(r[510:512])
}
func (r *BiosParameterBlock) SetSignature(value uint16) {
	binary.LittleEndian.PutUint16(r[510:512], value)
}
func (r BiosParameterBlock) Size() int64 {
	return 512
}
func (r BiosParameterBlock) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *BiosParameterBlock) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type BiosParameterBlock [512]byte
