// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: vibe_party/oci/proto/fetch_oci_image.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchOciImageDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registry      string                 `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Reference     string                 `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	Architecture  string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOciImageDefinition) Reset() {
	*x = FetchOciImageDefinition{}
	mi := &file_vibe_party_oci_proto_fetch_oci_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOciImageDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOciImageDefinition) ProtoMessage() {}

func (x *FetchOciImageDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_party_oci_proto_fetch_oci_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOciImageDefinition.ProtoReflect.Descriptor instead.
func (*FetchOciImageDefinition) Descriptor() ([]byte, []int) {
	return file_vibe_party_oci_proto_fetch_oci_image_proto_rawDescGZIP(), []int{0}
}

func (x *FetchOciImageDefinition) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *FetchOciImageDefinition) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *FetchOciImageDefinition) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *FetchOciImageDefinition) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

var File_vibe_party_oci_proto_fetch_oci_image_proto protoreflect.FileDescriptor

const file_vibe_party_oci_proto_fetch_oci_image_proto_rawDesc = "" +
	"\n" +
	"*vibe_party/oci/proto/fetch_oci_image.proto\x12\x05proto\"\x8d\x01\n" +
	"\x17FetchOciImageDefinition\x12\x1a\n" +
	"\bregistry\x18\x01 \x01(\tR\bregistry\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1c\n" +
	"\treference\x18\x03 \x01(\tR\treference\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitectureB5Z3github.com/tinyrange/tinyrange/vibe_party/oci/protob\x06proto3"

var (
	file_vibe_party_oci_proto_fetch_oci_image_proto_rawDescOnce sync.Once
	file_vibe_party_oci_proto_fetch_oci_image_proto_rawDescData []byte
)

func file_vibe_party_oci_proto_fetch_oci_image_proto_rawDescGZIP() []byte {
	file_vibe_party_oci_proto_fetch_oci_image_proto_rawDescOnce.Do(func() {
		file_vibe_party_oci_proto_fetch_oci_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vibe_party_oci_proto_fetch_oci_image_proto_rawDesc), len(file_vibe_party_oci_proto_fetch_oci_image_proto_rawDesc)))
	})
	return file_vibe_party_oci_proto_fetch_oci_image_proto_rawDescData
}

var file_vibe_party_oci_proto_fetch_oci_image_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vibe_party_oci_proto_fetch_oci_image_proto_goTypes = []any{
	(*FetchOciImageDefinition)(nil), // 0: proto.FetchOciImageDefinition
}
var file_vibe_party_oci_proto_fetch_oci_image_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vibe_party_oci_proto_fetch_oci_image_proto_init() }
func file_vibe_party_oci_proto_fetch_oci_image_proto_init() {
	if File_vibe_party_oci_proto_fetch_oci_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vibe_party_oci_proto_fetch_oci_image_proto_rawDesc), len(file_vibe_party_oci_proto_fetch_oci_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vibe_party_oci_proto_fetch_oci_image_proto_goTypes,
		DependencyIndexes: file_vibe_party_oci_proto_fetch_oci_image_proto_depIdxs,
		MessageInfos:      file_vibe_party_oci_proto_fetch_oci_image_proto_msgTypes,
	}.Build()
	File_vibe_party_oci_proto_fetch_oci_image_proto = out.File
	file_vibe_party_oci_proto_fetch_oci_image_proto_goTypes = nil
	file_vibe_party_oci_proto_fetch_oci_image_proto_depIdxs = nil
}
