// autogenerated by gen_protocol.py
package p9

import (
	"time"

	"github.com/tinyrange/tinyrange/pkg/common/binary"
)

type Tversion struct {
	Msize   uint32
	Version string
}

func (t *Tversion) Decode(r binary.BinaryReader) error {
	t.Msize = r.Uint32()
	t.Version = readString(r)
	return r.Error()
}

type Rversion struct {
	Msize   uint32
	Version string
}

func (t *Rversion) Encode(r binary.BinaryWriter) error {
	r.Uint32(t.Msize)
	writeString(r, t.Version)
	return r.Error()
}

type Tflush struct{ Oldtag uint16 }

func (t *Tflush) Decode(r binary.BinaryReader) error {
	t.Oldtag = r.Uint16()
	return r.Error()
}

type Rflush struct{}

func (t *Rflush) Encode(r binary.BinaryWriter) error {
	return r.Error()
}

type Twalk struct {
	Fid    uint32
	Newfid uint32
	Nwname []string
}

func (t *Twalk) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Newfid = r.Uint32()
	count := r.Uint16()
	for i := 0; i < int(count); i += 1 {
		t.Nwname = append(t.Nwname, readString(r))
	}
	return r.Error()
}

type Rwalk struct{ Nwqid []QID }

func (t *Rwalk) Encode(r binary.BinaryWriter) error {
	r.Uint16(uint16(len(t.Nwqid)))
	for _, q := range t.Nwqid {
		if err := q.Encode(r); err != nil {
			return err
		}
	}
	return r.Error()
}

type Tread struct {
	Fid    uint32
	Offset uint64
	Count  uint32
}

func (t *Tread) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Offset = r.Uint64()
	t.Count = r.Uint32()
	return r.Error()
}

type Rread struct {
	Count uint32
	Data  []byte
}

func (t *Rread) Encode(r binary.BinaryWriter) error {
	r.Uint32(t.Count)
	r.Bytes(t.Data)
	return r.Error()
}

type Twrite struct {
	Fid    uint32
	Offset uint64
	Count  uint32
	Data   []byte
}

func (t *Twrite) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Offset = r.Uint64()
	t.Count = r.Uint32()
	t.Data = r.Bytes(int(t.Count))
	return r.Error()
}

type Rwrite struct{ Count uint32 }

func (t *Rwrite) Encode(r binary.BinaryWriter) error {
	r.Uint32(t.Count)
	return r.Error()
}

type Tclunk struct{ Fid uint32 }

func (t *Tclunk) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	return r.Error()
}

type Rclunk struct{}

func (t *Rclunk) Encode(r binary.BinaryWriter) error {
	return r.Error()
}

type Tremove struct{ Fid uint32 }

func (t *Tremove) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	return r.Error()
}

type Rremove struct{}

func (t *Rremove) Encode(r binary.BinaryWriter) error {
	return r.Error()
}

type Tauth struct {
	Afid   uint32
	Uname  string
	Aname  string
	NUname uint32
}

func (t *Tauth) Decode(r binary.BinaryReader) error {
	t.Afid = r.Uint32()
	t.Uname = readString(r)
	t.Aname = readString(r)
	t.NUname = r.Uint32()
	return r.Error()
}

type Rauth struct{ Aqid QID }

func (t *Rauth) Encode(r binary.BinaryWriter) error {
	if err := t.Aqid.Encode(r); err != nil {
		return err
	}
	return r.Error()
}

type Tattach struct {
	Fid    uint32
	Afid   uint32
	Uname  string
	Aname  string
	NUname uint32
}

func (t *Tattach) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Afid = r.Uint32()
	t.Uname = readString(r)
	t.Aname = readString(r)
	t.NUname = r.Uint32()
	return r.Error()
}

type Rattach struct{ Qid QID }

func (t *Rattach) Encode(r binary.BinaryWriter) error {
	if err := t.Qid.Encode(r); err != nil {
		return err
	}
	return r.Error()
}

type Rlerror struct{ Ecode uint32 }

func (t *Rlerror) Encode(r binary.BinaryWriter) error {
	r.Uint32(t.Ecode)
	return r.Error()
}

type Tstatfs struct{ Fid uint32 }

func (t *Tstatfs) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	return r.Error()
}

type Rstatfs struct {
	Type    uint32
	Bsize   uint32
	Blocks  uint64
	Bfree   uint64
	Bavail  uint64
	Files   uint64
	Ffree   uint64
	Fsid    uint64
	Namelen uint32
}

func (t *Rstatfs) Encode(r binary.BinaryWriter) error {
	r.Uint32(t.Type)
	r.Uint32(t.Bsize)
	r.Uint64(t.Blocks)
	r.Uint64(t.Bfree)
	r.Uint64(t.Bavail)
	r.Uint64(t.Files)
	r.Uint64(t.Ffree)
	r.Uint64(t.Fsid)
	r.Uint32(t.Namelen)
	return r.Error()
}

type Tlopen struct {
	Fid   uint32
	Flags uint32
}

func (t *Tlopen) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Flags = r.Uint32()
	return r.Error()
}

type Rlopen struct {
	Qid    QID
	Iounit uint32
}

func (t *Rlopen) Encode(r binary.BinaryWriter) error {
	if err := t.Qid.Encode(r); err != nil {
		return err
	}
	r.Uint32(t.Iounit)
	return r.Error()
}

type Tlcreate struct {
	Fid   uint32
	Name  string
	Flags uint32
	Mode  uint32
	Gid   uint32
}

func (t *Tlcreate) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Name = readString(r)
	t.Flags = r.Uint32()
	t.Mode = r.Uint32()
	t.Gid = r.Uint32()
	return r.Error()
}

type Rlcreate struct {
	Qid    QID
	Iounit uint32
}

func (t *Rlcreate) Encode(r binary.BinaryWriter) error {
	if err := t.Qid.Encode(r); err != nil {
		return err
	}
	r.Uint32(t.Iounit)
	return r.Error()
}

type Tsymlink struct {
	Fid    uint32
	Name   string
	Symtgt string
	Gid    uint32
}

func (t *Tsymlink) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Name = readString(r)
	t.Symtgt = readString(r)
	t.Gid = r.Uint32()
	return r.Error()
}

type Rsymlink struct{ Qid QID }

func (t *Rsymlink) Encode(r binary.BinaryWriter) error {
	if err := t.Qid.Encode(r); err != nil {
		return err
	}
	return r.Error()
}

type Tmknod struct {
	Dfid  uint32
	Name  string
	Mode  uint32
	Major uint32
	Minor uint32
	Gid   uint32
}

func (t *Tmknod) Decode(r binary.BinaryReader) error {
	t.Dfid = r.Uint32()
	t.Name = readString(r)
	t.Mode = r.Uint32()
	t.Major = r.Uint32()
	t.Minor = r.Uint32()
	t.Gid = r.Uint32()
	return r.Error()
}

type Rmknod struct{ Qid QID }

func (t *Rmknod) Encode(r binary.BinaryWriter) error {
	if err := t.Qid.Encode(r); err != nil {
		return err
	}
	return r.Error()
}

type Trename struct {
	Fid  uint32
	Dfid uint32
	Name string
}

func (t *Trename) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Dfid = r.Uint32()
	t.Name = readString(r)
	return r.Error()
}

type Rrename struct{}

func (t *Rrename) Encode(r binary.BinaryWriter) error {
	return r.Error()
}

type Treadlink struct{ Fid uint32 }

func (t *Treadlink) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	return r.Error()
}

type Rreadlink struct{ Target string }

func (t *Rreadlink) Encode(r binary.BinaryWriter) error {
	writeString(r, t.Target)
	return r.Error()
}

type Tgetattr struct {
	Fid         uint32
	RequestMask uint64
}

func (t *Tgetattr) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.RequestMask = r.Uint64()
	return r.Error()
}

type Rgetattr struct {
	Valid       uint64
	Qid         QID
	Mode        uint32
	Uid         uint32
	Gid         uint32
	Nlink       uint64
	Rdev        uint64
	Size        uint64
	Blksize     uint64
	Blocks      uint64
	Atime       time.Time
	Mtime       time.Time
	Ctime       time.Time
	Btime       time.Time
	Gen         uint64
	DataVersion uint64
}

func (t *Rgetattr) Encode(r binary.BinaryWriter) error {
	r.Uint64(t.Valid)
	if err := t.Qid.Encode(r); err != nil {
		return err
	}
	r.Uint32(t.Mode)
	r.Uint32(t.Uid)
	r.Uint32(t.Gid)
	r.Uint64(t.Nlink)
	r.Uint64(t.Rdev)
	r.Uint64(t.Size)
	r.Uint64(t.Blksize)
	r.Uint64(t.Blocks)
	r.Uint64(uint64(t.Atime.Unix()))
	r.Uint64(uint64(t.Atime.Nanosecond()))
	r.Uint64(uint64(t.Mtime.Unix()))
	r.Uint64(uint64(t.Mtime.Nanosecond()))
	r.Uint64(uint64(t.Ctime.Unix()))
	r.Uint64(uint64(t.Ctime.Nanosecond()))
	r.Uint64(uint64(t.Btime.Unix()))
	r.Uint64(uint64(t.Btime.Nanosecond()))
	r.Uint64(t.Gen)
	r.Uint64(t.DataVersion)
	return r.Error()
}

type Tsetattr struct {
	Fid   uint32
	Valid uint32
	Mode  uint32
	Uid   uint32
	Gid   uint32
	Size  uint64
	Atime time.Time
	Mtime time.Time
}

func (t *Tsetattr) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Valid = r.Uint32()
	t.Mode = r.Uint32()
	t.Uid = r.Uint32()
	t.Gid = r.Uint32()
	t.Size = r.Uint64()
	t.Atime = time.Unix(int64(r.Uint64()), int64(r.Uint64()))
	t.Mtime = time.Unix(int64(r.Uint64()), int64(r.Uint64()))
	return r.Error()
}

type Rsetattr struct{}

func (t *Rsetattr) Encode(r binary.BinaryWriter) error {
	return r.Error()
}

type Txattrwalk struct {
	Fid    uint32
	Newfid uint32
	Name   string
}

func (t *Txattrwalk) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Newfid = r.Uint32()
	t.Name = readString(r)
	return r.Error()
}

type Rxattrwalk struct{ Size uint64 }

func (t *Rxattrwalk) Encode(r binary.BinaryWriter) error {
	r.Uint64(t.Size)
	return r.Error()
}

type Txattrcreate struct {
	Fid      uint32
	Name     string
	AttrSize uint64
	Flags    uint32
}

func (t *Txattrcreate) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Name = readString(r)
	t.AttrSize = r.Uint64()
	t.Flags = r.Uint32()
	return r.Error()
}

type Rxattrcreate struct{}

func (t *Rxattrcreate) Encode(r binary.BinaryWriter) error {
	return r.Error()
}

type Treaddir struct {
	Fid    uint32
	Offset uint64
	Count  uint32
}

func (t *Treaddir) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Offset = r.Uint64()
	t.Count = r.Uint32()
	return r.Error()
}

type Dirent struct {
	Qid    QID
	Offset uint64
	Type   uint8
	Name   string
}

func (t *Dirent) Encode(r binary.BinaryWriter) error {
	if err := t.Qid.Encode(r); err != nil {
		return err
	}
	r.Uint64(t.Offset)
	r.Uint8(t.Type)
	writeString(r, t.Name)
	return r.Error()
}

type Rreaddir struct {
	Count uint32
	Data  []Dirent
}

func (t *Rreaddir) Encode(r binary.BinaryWriter) error {
	r.Uint32(t.Count)
	for _, d := range t.Data {
		if err := d.Encode(r); err != nil {
			return err
		}
	}
	return r.Error()
}

type Tfsync struct{ Fid uint32 }

func (t *Tfsync) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	return r.Error()
}

type Rfsync struct{}

func (t *Rfsync) Encode(r binary.BinaryWriter) error {
	return r.Error()
}

type Tlock struct {
	Fid      uint32
	Type     uint8
	Flags    uint32
	Start    uint64
	Length   uint64
	ProcId   uint32
	ClientId string
}

func (t *Tlock) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Type = r.Uint8()
	t.Flags = r.Uint32()
	t.Start = r.Uint64()
	t.Length = r.Uint64()
	t.ProcId = r.Uint32()
	t.ClientId = readString(r)
	return r.Error()
}

type Rlock struct{ Status uint8 }

func (t *Rlock) Encode(r binary.BinaryWriter) error {
	r.Uint8(t.Status)
	return r.Error()
}

type Tgetlock struct {
	Fid      uint32
	Type     uint8
	Start    uint64
	Length   uint64
	ProcId   uint32
	ClientId string
}

func (t *Tgetlock) Decode(r binary.BinaryReader) error {
	t.Fid = r.Uint32()
	t.Type = r.Uint8()
	t.Start = r.Uint64()
	t.Length = r.Uint64()
	t.ProcId = r.Uint32()
	t.ClientId = readString(r)
	return r.Error()
}

type Rgetlock struct {
	Type     uint8
	Start    uint64
	Length   uint64
	ProcId   uint32
	ClientId string
}

func (t *Rgetlock) Encode(r binary.BinaryWriter) error {
	r.Uint8(t.Type)
	r.Uint64(t.Start)
	r.Uint64(t.Length)
	r.Uint32(t.ProcId)
	writeString(r, t.ClientId)
	return r.Error()
}

type Tlink struct {
	Dfid uint32
	Fid  uint32
	Name string
}

func (t *Tlink) Decode(r binary.BinaryReader) error {
	t.Dfid = r.Uint32()
	t.Fid = r.Uint32()
	t.Name = readString(r)
	return r.Error()
}

type Rlink struct{}

func (t *Rlink) Encode(r binary.BinaryWriter) error {
	return r.Error()
}

type Tmkdir struct {
	Dfid uint32
	Name string
	Mode uint32
	Gid  uint32
}

func (t *Tmkdir) Decode(r binary.BinaryReader) error {
	t.Dfid = r.Uint32()
	t.Name = readString(r)
	t.Mode = r.Uint32()
	t.Gid = r.Uint32()
	return r.Error()
}

type Rmkdir struct{ Qid QID }

func (t *Rmkdir) Encode(r binary.BinaryWriter) error {
	if err := t.Qid.Encode(r); err != nil {
		return err
	}
	return r.Error()
}

type Trenameat struct {
	Olddirfid uint32
	Oldname   string
	Newdirfid uint32
	Newname   string
}

func (t *Trenameat) Decode(r binary.BinaryReader) error {
	t.Olddirfid = r.Uint32()
	t.Oldname = readString(r)
	t.Newdirfid = r.Uint32()
	t.Newname = readString(r)
	return r.Error()
}

type Rrenameat struct{}

func (t *Rrenameat) Encode(r binary.BinaryWriter) error {
	return r.Error()
}

type Tunlinkat struct {
	Dirfd uint32
	Name  string
	Flags uint32
}

func (t *Tunlinkat) Decode(r binary.BinaryReader) error {
	t.Dirfd = r.Uint32()
	t.Name = readString(r)
	t.Flags = r.Uint32()
	return r.Error()
}

type Runlinkat struct{}

func (t *Runlinkat) Encode(r binary.BinaryWriter) error {
	return r.Error()
}

var (
	_ binary.Decodable = &Tversion{}
	_ binary.Encodable = &Rversion{}
	_ binary.Decodable = &Tflush{}
	_ binary.Encodable = &Rflush{}
	_ binary.Decodable = &Twalk{}
	_ binary.Encodable = &Rwalk{}
	_ binary.Decodable = &Tread{}
	_ binary.Encodable = &Rread{}
	_ binary.Decodable = &Twrite{}
	_ binary.Encodable = &Rwrite{}
	_ binary.Decodable = &Tclunk{}
	_ binary.Encodable = &Rclunk{}
	_ binary.Decodable = &Tremove{}
	_ binary.Encodable = &Rremove{}
	_ binary.Decodable = &Tauth{}
	_ binary.Encodable = &Rauth{}
	_ binary.Decodable = &Tattach{}
	_ binary.Encodable = &Rattach{}
	_ binary.Encodable = &Rlerror{}
	_ binary.Decodable = &Tstatfs{}
	_ binary.Encodable = &Rstatfs{}
	_ binary.Decodable = &Tlopen{}
	_ binary.Encodable = &Rlopen{}
	_ binary.Decodable = &Tlcreate{}
	_ binary.Encodable = &Rlcreate{}
	_ binary.Decodable = &Tsymlink{}
	_ binary.Encodable = &Rsymlink{}
	_ binary.Decodable = &Tmknod{}
	_ binary.Encodable = &Rmknod{}
	_ binary.Decodable = &Trename{}
	_ binary.Encodable = &Rrename{}
	_ binary.Decodable = &Treadlink{}
	_ binary.Encodable = &Rreadlink{}
	_ binary.Decodable = &Tgetattr{}
	_ binary.Encodable = &Rgetattr{}
	_ binary.Decodable = &Tsetattr{}
	_ binary.Encodable = &Rsetattr{}
	_ binary.Decodable = &Txattrwalk{}
	_ binary.Encodable = &Rxattrwalk{}
	_ binary.Decodable = &Txattrcreate{}
	_ binary.Encodable = &Rxattrcreate{}
	_ binary.Decodable = &Treaddir{}
	_ binary.Encodable = &Dirent{}
	_ binary.Encodable = &Rreaddir{}
	_ binary.Decodable = &Tfsync{}
	_ binary.Encodable = &Rfsync{}
	_ binary.Decodable = &Tlock{}
	_ binary.Encodable = &Rlock{}
	_ binary.Decodable = &Tgetlock{}
	_ binary.Encodable = &Rgetlock{}
	_ binary.Decodable = &Tlink{}
	_ binary.Encodable = &Rlink{}
	_ binary.Decodable = &Tmkdir{}
	_ binary.Encodable = &Rmkdir{}
	_ binary.Decodable = &Trenameat{}
	_ binary.Encodable = &Rrenameat{}
	_ binary.Decodable = &Tunlinkat{}
	_ binary.Encodable = &Runlinkat{}
)
