// generated by structGen. DO NOT EDIT MANUALLY

package test

import "encoding/binary"

func (r Simple) ASlice() [1]byte {
	return [1]byte(r[0:1])
}
func (r Simple) GetA() uint8 {
	return uint8(r[0:1][0])
}
func (r *Simple) SetA(value uint8) {
	r[0:1][0] = byte(value)
}
func (r Simple) BSlice() [2]byte {
	return [2]byte(r[1:3])
}
func (r Simple) GetB() uint16 {
	return binary.LittleEndian.Uint16(r[1:3])
}
func (r *Simple) SetB(value uint16) {
	binary.LittleEndian.PutUint16(r[1:3], value)
}
func (r Simple) CSlice() [4]byte {
	return [4]byte(r[3:7])
}
func (r Simple) GetC() uint32 {
	return binary.LittleEndian.Uint32(r[3:7])
}
func (r *Simple) SetC(value uint32) {
	binary.LittleEndian.PutUint32(r[3:7], value)
}
func (r Simple) DSlice() [4]byte {
	return [4]byte(r[7:11])
}
func (r Simple) GetD() int32 {
	return int32(binary.LittleEndian.Uint32(r[7:11]))
}
func (r *Simple) SetD(value int32) {
	binary.LittleEndian.PutUint32(r[7:11], uint32(value))
}
func (r Simple) Size() int64 {
	return 1 + 2 + 4 + 4
}

type Simple [1 + 2 + 4 + 4]byte

func (r Simple2) ASlice() [11]byte {
	return [11]byte(r[0:11])
}
func (r Simple2) GetA() Simple {
	return Simple(r[0:11])
}
func (r *Simple2) SetA(value Simple) {
	copy(r[0:11], value[:])
}
func (r Simple2) BSlice() [11]byte {
	return [11]byte(r[11:22])
}
func (r Simple2) GetB() Simple {
	return Simple(r[11:22])
}
func (r *Simple2) SetB(value Simple) {
	copy(r[11:22], value[:])
}
func (r Simple2) Size() int64 {
	return 11 + 11
}

type Simple2 [11 + 11]byte
type SimpleUnion [11]byte
