// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: machine.proto

package machinepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenSocketRequest_Protocol int32

const (
	OpenSocketRequest_PROTO_TCP OpenSocketRequest_Protocol = 0
	OpenSocketRequest_PROTO_UDP OpenSocketRequest_Protocol = 1
)

// Enum value maps for OpenSocketRequest_Protocol.
var (
	OpenSocketRequest_Protocol_name = map[int32]string{
		0: "PROTO_TCP",
		1: "PROTO_UDP",
	}
	OpenSocketRequest_Protocol_value = map[string]int32{
		"PROTO_TCP": 0,
		"PROTO_UDP": 1,
	}
)

func (x OpenSocketRequest_Protocol) Enum() *OpenSocketRequest_Protocol {
	p := new(OpenSocketRequest_Protocol)
	*p = x
	return p
}

func (x OpenSocketRequest_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenSocketRequest_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_machine_proto_enumTypes[0].Descriptor()
}

func (OpenSocketRequest_Protocol) Type() protoreflect.EnumType {
	return &file_machine_proto_enumTypes[0]
}

func (x OpenSocketRequest_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenSocketRequest_Protocol.Descriptor instead.
func (OpenSocketRequest_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{14, 0}
}

// ** File Operations **
type OpenFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                          // Path of the file to open
	ForRead       bool                   `protobuf:"varint,2,opt,name=for_read,json=forRead,proto3" json:"for_read,omitempty"`    // Open for reading
	ForWrite      bool                   `protobuf:"varint,3,opt,name=for_write,json=forWrite,proto3" json:"for_write,omitempty"` // Open for writing
	Create        bool                   `protobuf:"varint,4,opt,name=create,proto3" json:"create,omitempty"`                     // Create file if not exists
	Truncate      bool                   `protobuf:"varint,5,opt,name=truncate,proto3" json:"truncate,omitempty"`                 // Truncate file if exists and opening for write
	Mode          uint32                 `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`                         // (Optional) file permission bits for creation (e.g., 0644),
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFileRequest) Reset() {
	*x = OpenFileRequest{}
	mi := &file_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileRequest) ProtoMessage() {}

func (x *OpenFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileRequest.ProtoReflect.Descriptor instead.
func (*OpenFileRequest) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{0}
}

func (x *OpenFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OpenFileRequest) GetForRead() bool {
	if x != nil {
		return x.ForRead
	}
	return false
}

func (x *OpenFileRequest) GetForWrite() bool {
	if x != nil {
		return x.ForWrite
	}
	return false
}

func (x *OpenFileRequest) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

func (x *OpenFileRequest) GetTruncate() bool {
	if x != nil {
		return x.Truncate
	}
	return false
}

func (x *OpenFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type OpenFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"` // File descriptor (handle) for the opened file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFileResponse) Reset() {
	*x = OpenFileResponse{}
	mi := &file_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileResponse) ProtoMessage() {}

func (x *OpenFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileResponse.ProtoReflect.Descriptor instead.
func (*OpenFileResponse) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{1}
}

func (x *OpenFileResponse) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`                             // Handle to read from (file, socket, or process stream)
	MaxBytes      uint32                 `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"` // Maximum bytes to read in one chunk (hint, not strict)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRequest) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *ReadRequest) GetMaxBytes() uint32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Data read (up to max_bytes, or less if stream had less available)
	Eof           bool                   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`  // True if end-of-file/stream is reached (no more data)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_machine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`    // Handle to write to (file, socket, or process stream)
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // Chunk of data to write
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_machine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{4}
}

func (x *WriteRequest) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  uint64                 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"` // Total bytes successfully written (could be less
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_machine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{5}
}

func (x *WriteResponse) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"` // Handle to close
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_machine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{6}
}

func (x *CloseRequest) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_machine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{7}
}

func (x *CloseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ** Process Execution **
type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`                                                                   // Path to executable or command name
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`                                                                         // Command-line arguments
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables (KEY=VALUE), optional
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`                                           // Working directory for the process, optional
	Tty           bool                   `protobuf:"varint,5,opt,name=tty,proto3" json:"tty,omitempty"`                                                                          // Allocate a pseudo-terminal (TTY) for the process (if
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_machine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{8}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecRequest) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`                           // Process ID or handle of the started process
	StdinFd       int32                  `protobuf:"varint,2,opt,name=stdin_fd,json=stdinFd,proto3" json:"stdin_fd,omitempty"`    // File descriptor for writing to process stdin
	StdoutFd      int32                  `protobuf:"varint,3,opt,name=stdout_fd,json=stdoutFd,proto3" json:"stdout_fd,omitempty"` // File descriptor for reading process stdout
	StderrFd      int32                  `protobuf:"varint,4,opt,name=stderr_fd,json=stderrFd,proto3" json:"stderr_fd,omitempty"` // File descriptor for reading process stderr (if tty=false)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_machine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{9}
}

func (x *ExecResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ExecResponse) GetStdinFd() int32 {
	if x != nil {
		return x.StdinFd
	}
	return 0
}

func (x *ExecResponse) GetStdoutFd() int32 {
	if x != nil {
		return x.StdoutFd
	}
	return 0
}

func (x *ExecResponse) GetStderrFd() int32 {
	if x != nil {
		return x.StderrFd
	}
	return 0
}

type SignalProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`       // Process ID/handle to signal
	Signal        int32                  `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"` // Signal number (e.g., 15 for SIGTERM, 9 for SIGKILL). On
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalProcessRequest) Reset() {
	*x = SignalProcessRequest{}
	mi := &file_machine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalProcessRequest) ProtoMessage() {}

func (x *SignalProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalProcessRequest.ProtoReflect.Descriptor instead.
func (*SignalProcessRequest) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{10}
}

func (x *SignalProcessRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SignalProcessRequest) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

type SignalProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalProcessResponse) Reset() {
	*x = SignalProcessResponse{}
	mi := &file_machine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalProcessResponse) ProtoMessage() {}

func (x *SignalProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalProcessResponse.ProtoReflect.Descriptor instead.
func (*SignalProcessResponse) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{11}
}

func (x *SignalProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WaitProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitProcessRequest) Reset() {
	*x = WaitProcessRequest{}
	mi := &file_machine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitProcessRequest) ProtoMessage() {}

func (x *WaitProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitProcessRequest.ProtoReflect.Descriptor instead.
func (*WaitProcessRequest) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{12}
}

func (x *WaitProcessRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type WaitProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitProcessResponse) Reset() {
	*x = WaitProcessResponse{}
	mi := &file_machine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitProcessResponse) ProtoMessage() {}

func (x *WaitProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitProcessResponse.ProtoReflect.Descriptor instead.
func (*WaitProcessResponse) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{13}
}

func (x *WaitProcessResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// ** Network Socket Operations **
type OpenSocketRequest struct {
	state    protoimpl.MessageState     `protogen:"open.v1"`
	Protocol OpenSocketRequest_Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=remote.machine.OpenSocketRequest_Protocol" json:"protocol,omitempty"`
	Listen   bool                       `protobuf:"varint,2,opt,name=listen,proto3" json:"listen,omitempty"` // If true, create a server socket (bind and listen). If
	// false, create a client socket.
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` // Address to bind or connect to (e.g., "0.0.0.0" for
	// listen or remote host for connect)
	Port          uint32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"` // Port to bind or connect.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSocketRequest) Reset() {
	*x = OpenSocketRequest{}
	mi := &file_machine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSocketRequest) ProtoMessage() {}

func (x *OpenSocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSocketRequest.ProtoReflect.Descriptor instead.
func (*OpenSocketRequest) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{14}
}

func (x *OpenSocketRequest) GetProtocol() OpenSocketRequest_Protocol {
	if x != nil {
		return x.Protocol
	}
	return OpenSocketRequest_PROTO_TCP
}

func (x *OpenSocketRequest) GetListen() bool {
	if x != nil {
		return x.Listen
	}
	return false
}

func (x *OpenSocketRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OpenSocketRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type OpenSocketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"` // Socket handle (listening socket or connected socket)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSocketResponse) Reset() {
	*x = OpenSocketResponse{}
	mi := &file_machine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSocketResponse) ProtoMessage() {}

func (x *OpenSocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSocketResponse.ProtoReflect.Descriptor instead.
func (*OpenSocketResponse) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{15}
}

func (x *OpenSocketResponse) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerFd      int32                  `protobuf:"varint,1,opt,name=server_fd,json=serverFd,proto3" json:"server_fd,omitempty"` // The file descriptor of a listening socket (from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_machine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{16}
}

func (x *AcceptRequest) GetServerFd() int32 {
	if x != nil {
		return x.ServerFd
	}
	return 0
}

type AcceptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientFd      int32                  `protobuf:"varint,1,opt,name=client_fd,json=clientFd,proto3" json:"client_fd,omitempty"`               // New socket descriptor for the accepted connection
	RemoteAddress string                 `protobuf:"bytes,2,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"` // Remote peer address (for info)
	RemotePort    uint32                 `protobuf:"varint,3,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`         // Remote peer port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_machine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{17}
}

func (x *AcceptResponse) GetClientFd() int32 {
	if x != nil {
		return x.ClientFd
	}
	return 0
}

func (x *AcceptResponse) GetRemoteAddress() string {
	if x != nil {
		return x.RemoteAddress
	}
	return ""
}

func (x *AcceptResponse) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

// Mkdir
type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`       // e.g., 0755
	Parents       bool                   `protobuf:"varint,3,opt,name=parents,proto3" json:"parents,omitempty"` // if true, create parent directories as needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_machine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{18}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MkdirRequest) GetParents() bool {
	if x != nil {
		return x.Parents
	}
	return false
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_machine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{19}
}

func (x *MkdirResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Stat
type StatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	FollowSymlinks bool                   `protobuf:"varint,2,opt,name=follow_symlinks,json=followSymlinks,proto3" json:"follow_symlinks,omitempty"` // if true, follow symlinks to their target
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_machine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{20}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StatRequest) GetFollowSymlinks() bool {
	if x != nil {
		return x.FollowSymlinks
	}
	return false
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                            // bytes
	Mode          uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`                            // permission bits
	MtimeSec      int64                  `protobuf:"varint,6,opt,name=mtime_sec,json=mtimeSec,proto3" json:"mtime_sec,omitempty"`    // last modified (unix seconds)
	MtimeNsec     int64                  `protobuf:"varint,7,opt,name=mtime_nsec,json=mtimeNsec,proto3" json:"mtime_nsec,omitempty"` // last modified (nsec part)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_machine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{21}
}

func (x *StatResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StatResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *StatResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StatResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatResponse) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *StatResponse) GetMtimeSec() int64 {
	if x != nil {
		return x.MtimeSec
	}
	return 0
}

func (x *StatResponse) GetMtimeNsec() int64 {
	if x != nil {
		return x.MtimeNsec
	}
	return 0
}

// Chmod
type ChmodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodRequest) Reset() {
	*x = ChmodRequest{}
	mi := &file_machine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodRequest) ProtoMessage() {}

func (x *ChmodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodRequest.ProtoReflect.Descriptor instead.
func (*ChmodRequest) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{22}
}

func (x *ChmodRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChmodRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type ChmodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodResponse) Reset() {
	*x = ChmodResponse{}
	mi := &file_machine_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodResponse) ProtoMessage() {}

func (x *ChmodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodResponse.ProtoReflect.Descriptor instead.
func (*ChmodResponse) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{23}
}

func (x *ChmodResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Chown
type ChownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Uid           int32                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           int32                  `protobuf:"varint,3,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChownRequest) Reset() {
	*x = ChownRequest{}
	mi := &file_machine_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChownRequest) ProtoMessage() {}

func (x *ChownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChownRequest.ProtoReflect.Descriptor instead.
func (*ChownRequest) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{24}
}

func (x *ChownRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChownRequest) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ChownRequest) GetGid() int32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type ChownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChownResponse) Reset() {
	*x = ChownResponse{}
	mi := &file_machine_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChownResponse) ProtoMessage() {}

func (x *ChownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChownResponse.ProtoReflect.Descriptor instead.
func (*ChownResponse) Descriptor() ([]byte, []int) {
	return file_machine_proto_rawDescGZIP(), []int{25}
}

func (x *ChownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_machine_proto protoreflect.FileDescriptor

const file_machine_proto_rawDesc = "" +
	"\n" +
	"\rmachine.proto\x12\x0eremote.machine\"\xa5\x01\n" +
	"\x0fOpenFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bfor_read\x18\x02 \x01(\bR\aforRead\x12\x1b\n" +
	"\tfor_write\x18\x03 \x01(\bR\bforWrite\x12\x16\n" +
	"\x06create\x18\x04 \x01(\bR\x06create\x12\x1a\n" +
	"\btruncate\x18\x05 \x01(\bR\btruncate\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\rR\x04mode\"\"\n" +
	"\x10OpenFileResponse\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\":\n" +
	"\vReadRequest\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\rR\bmaxBytes\"4\n" +
	"\fReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof\"2\n" +
	"\fWriteRequest\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"4\n" +
	"\rWriteResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x04R\fbytesWritten\"\x1e\n" +
	"\fCloseRequest\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\")\n" +
	"\rCloseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xde\x01\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x126\n" +
	"\x03env\x18\x03 \x03(\v2$.remote.machine.ExecRequest.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12\x10\n" +
	"\x03tty\x18\x05 \x01(\bR\x03tty\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\fExecResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x19\n" +
	"\bstdin_fd\x18\x02 \x01(\x05R\astdinFd\x12\x1b\n" +
	"\tstdout_fd\x18\x03 \x01(\x05R\bstdoutFd\x12\x1b\n" +
	"\tstderr_fd\x18\x04 \x01(\x05R\bstderrFd\"@\n" +
	"\x14SignalProcessRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\x05R\x06signal\"1\n" +
	"\x15SignalProcessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\x12WaitProcessRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"2\n" +
	"\x13WaitProcessResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"\xcb\x01\n" +
	"\x11OpenSocketRequest\x12F\n" +
	"\bprotocol\x18\x01 \x01(\x0e2*.remote.machine.OpenSocketRequest.ProtocolR\bprotocol\x12\x16\n" +
	"\x06listen\x18\x02 \x01(\bR\x06listen\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\"(\n" +
	"\bProtocol\x12\r\n" +
	"\tPROTO_TCP\x10\x00\x12\r\n" +
	"\tPROTO_UDP\x10\x01\"$\n" +
	"\x12OpenSocketResponse\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\",\n" +
	"\rAcceptRequest\x12\x1b\n" +
	"\tserver_fd\x18\x01 \x01(\x05R\bserverFd\"u\n" +
	"\x0eAcceptResponse\x12\x1b\n" +
	"\tclient_fd\x18\x01 \x01(\x05R\bclientFd\x12%\n" +
	"\x0eremote_address\x18\x02 \x01(\tR\rremoteAddress\x12\x1f\n" +
	"\vremote_port\x18\x03 \x01(\rR\n" +
	"remotePort\"P\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x18\n" +
	"\aparents\x18\x03 \x01(\bR\aparents\")\n" +
	"\rMkdirResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12'\n" +
	"\x0ffollow_symlinks\x18\x02 \x01(\bR\x0efollowSymlinks\"\xb5\x01\n" +
	"\fStatResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\x12\x1b\n" +
	"\tmtime_sec\x18\x06 \x01(\x03R\bmtimeSec\x12\x1d\n" +
	"\n" +
	"mtime_nsec\x18\a \x01(\x03R\tmtimeNsec\"6\n" +
	"\fChmodRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\")\n" +
	"\rChmodResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\fChownRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x05R\x03uid\x12\x10\n" +
	"\x03gid\x18\x03 \x01(\x05R\x03gid\")\n" +
	"\rChownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xde\a\n" +
	"\x0eMachineService\x12M\n" +
	"\bOpenFile\x12\x1f.remote.machine.OpenFileRequest\x1a .remote.machine.OpenFileResponse\x12C\n" +
	"\x04Read\x12\x1b.remote.machine.ReadRequest\x1a\x1c.remote.machine.ReadResponse0\x01\x12F\n" +
	"\x05Write\x12\x1c.remote.machine.WriteRequest\x1a\x1d.remote.machine.WriteResponse(\x01\x12D\n" +
	"\x05Close\x12\x1c.remote.machine.CloseRequest\x1a\x1d.remote.machine.CloseResponse\x12A\n" +
	"\x04Exec\x12\x1b.remote.machine.ExecRequest\x1a\x1c.remote.machine.ExecResponse\x12\\\n" +
	"\rSignalProcess\x12$.remote.machine.SignalProcessRequest\x1a%.remote.machine.SignalProcessResponse\x12V\n" +
	"\vWaitProcess\x12\".remote.machine.WaitProcessRequest\x1a#.remote.machine.WaitProcessResponse\x12S\n" +
	"\n" +
	"OpenSocket\x12!.remote.machine.OpenSocketRequest\x1a\".remote.machine.OpenSocketResponse\x12G\n" +
	"\x06Accept\x12\x1d.remote.machine.AcceptRequest\x1a\x1e.remote.machine.AcceptResponse\x12D\n" +
	"\x05Mkdir\x12\x1c.remote.machine.MkdirRequest\x1a\x1d.remote.machine.MkdirResponse\x12A\n" +
	"\x04Stat\x12\x1b.remote.machine.StatRequest\x1a\x1c.remote.machine.StatResponse\x12D\n" +
	"\x05Chmod\x12\x1c.remote.machine.ChmodRequest\x1a\x1d.remote.machine.ChmodResponse\x12D\n" +
	"\x05Chown\x12\x1c.remote.machine.ChownRequest\x1a\x1d.remote.machine.ChownResponseB&Z$example.com/remote/machine;machinepbb\x06proto3"

var (
	file_machine_proto_rawDescOnce sync.Once
	file_machine_proto_rawDescData []byte
)

func file_machine_proto_rawDescGZIP() []byte {
	file_machine_proto_rawDescOnce.Do(func() {
		file_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_machine_proto_rawDesc), len(file_machine_proto_rawDesc)))
	})
	return file_machine_proto_rawDescData
}

var file_machine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_machine_proto_goTypes = []any{
	(OpenSocketRequest_Protocol)(0), // 0: remote.machine.OpenSocketRequest.Protocol
	(*OpenFileRequest)(nil),         // 1: remote.machine.OpenFileRequest
	(*OpenFileResponse)(nil),        // 2: remote.machine.OpenFileResponse
	(*ReadRequest)(nil),             // 3: remote.machine.ReadRequest
	(*ReadResponse)(nil),            // 4: remote.machine.ReadResponse
	(*WriteRequest)(nil),            // 5: remote.machine.WriteRequest
	(*WriteResponse)(nil),           // 6: remote.machine.WriteResponse
	(*CloseRequest)(nil),            // 7: remote.machine.CloseRequest
	(*CloseResponse)(nil),           // 8: remote.machine.CloseResponse
	(*ExecRequest)(nil),             // 9: remote.machine.ExecRequest
	(*ExecResponse)(nil),            // 10: remote.machine.ExecResponse
	(*SignalProcessRequest)(nil),    // 11: remote.machine.SignalProcessRequest
	(*SignalProcessResponse)(nil),   // 12: remote.machine.SignalProcessResponse
	(*WaitProcessRequest)(nil),      // 13: remote.machine.WaitProcessRequest
	(*WaitProcessResponse)(nil),     // 14: remote.machine.WaitProcessResponse
	(*OpenSocketRequest)(nil),       // 15: remote.machine.OpenSocketRequest
	(*OpenSocketResponse)(nil),      // 16: remote.machine.OpenSocketResponse
	(*AcceptRequest)(nil),           // 17: remote.machine.AcceptRequest
	(*AcceptResponse)(nil),          // 18: remote.machine.AcceptResponse
	(*MkdirRequest)(nil),            // 19: remote.machine.MkdirRequest
	(*MkdirResponse)(nil),           // 20: remote.machine.MkdirResponse
	(*StatRequest)(nil),             // 21: remote.machine.StatRequest
	(*StatResponse)(nil),            // 22: remote.machine.StatResponse
	(*ChmodRequest)(nil),            // 23: remote.machine.ChmodRequest
	(*ChmodResponse)(nil),           // 24: remote.machine.ChmodResponse
	(*ChownRequest)(nil),            // 25: remote.machine.ChownRequest
	(*ChownResponse)(nil),           // 26: remote.machine.ChownResponse
	nil,                             // 27: remote.machine.ExecRequest.EnvEntry
}
var file_machine_proto_depIdxs = []int32{
	27, // 0: remote.machine.ExecRequest.env:type_name -> remote.machine.ExecRequest.EnvEntry
	0,  // 1: remote.machine.OpenSocketRequest.protocol:type_name -> remote.machine.OpenSocketRequest.Protocol
	1,  // 2: remote.machine.MachineService.OpenFile:input_type -> remote.machine.OpenFileRequest
	3,  // 3: remote.machine.MachineService.Read:input_type -> remote.machine.ReadRequest
	5,  // 4: remote.machine.MachineService.Write:input_type -> remote.machine.WriteRequest
	7,  // 5: remote.machine.MachineService.Close:input_type -> remote.machine.CloseRequest
	9,  // 6: remote.machine.MachineService.Exec:input_type -> remote.machine.ExecRequest
	11, // 7: remote.machine.MachineService.SignalProcess:input_type -> remote.machine.SignalProcessRequest
	13, // 8: remote.machine.MachineService.WaitProcess:input_type -> remote.machine.WaitProcessRequest
	15, // 9: remote.machine.MachineService.OpenSocket:input_type -> remote.machine.OpenSocketRequest
	17, // 10: remote.machine.MachineService.Accept:input_type -> remote.machine.AcceptRequest
	19, // 11: remote.machine.MachineService.Mkdir:input_type -> remote.machine.MkdirRequest
	21, // 12: remote.machine.MachineService.Stat:input_type -> remote.machine.StatRequest
	23, // 13: remote.machine.MachineService.Chmod:input_type -> remote.machine.ChmodRequest
	25, // 14: remote.machine.MachineService.Chown:input_type -> remote.machine.ChownRequest
	2,  // 15: remote.machine.MachineService.OpenFile:output_type -> remote.machine.OpenFileResponse
	4,  // 16: remote.machine.MachineService.Read:output_type -> remote.machine.ReadResponse
	6,  // 17: remote.machine.MachineService.Write:output_type -> remote.machine.WriteResponse
	8,  // 18: remote.machine.MachineService.Close:output_type -> remote.machine.CloseResponse
	10, // 19: remote.machine.MachineService.Exec:output_type -> remote.machine.ExecResponse
	12, // 20: remote.machine.MachineService.SignalProcess:output_type -> remote.machine.SignalProcessResponse
	14, // 21: remote.machine.MachineService.WaitProcess:output_type -> remote.machine.WaitProcessResponse
	16, // 22: remote.machine.MachineService.OpenSocket:output_type -> remote.machine.OpenSocketResponse
	18, // 23: remote.machine.MachineService.Accept:output_type -> remote.machine.AcceptResponse
	20, // 24: remote.machine.MachineService.Mkdir:output_type -> remote.machine.MkdirResponse
	22, // 25: remote.machine.MachineService.Stat:output_type -> remote.machine.StatResponse
	24, // 26: remote.machine.MachineService.Chmod:output_type -> remote.machine.ChmodResponse
	26, // 27: remote.machine.MachineService.Chown:output_type -> remote.machine.ChownResponse
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_machine_proto_init() }
func file_machine_proto_init() {
	if File_machine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_machine_proto_rawDesc), len(file_machine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_machine_proto_goTypes,
		DependencyIndexes: file_machine_proto_depIdxs,
		EnumInfos:         file_machine_proto_enumTypes,
		MessageInfos:      file_machine_proto_msgTypes,
	}.Build()
	File_machine_proto = out.File
	file_machine_proto_goTypes = nil
	file_machine_proto_depIdxs = nil
}
