// generated by structGen. DO NOT EDIT MANUALLY

package main

import (
	"encoding/binary"
	"io"
)

type VolumeDescriptorKind uint8

const VolumeDescriptorKindBootRecord VolumeDescriptorKind = 0
const VolumeDescriptorKindPrimary VolumeDescriptorKind = 1
const VolumeDescriptorKindSupplementary VolumeDescriptorKind = 2
const VolumeDescriptorKindPartition VolumeDescriptorKind = 3
const VolumeDescriptorKindTerminator VolumeDescriptorKind = 255

func (e VolumeDescriptorKind) String() string {
	switch e {
	case VolumeDescriptorKindBootRecord:
		return "BootRecord"
	case VolumeDescriptorKindPrimary:
		return "Primary"
	case VolumeDescriptorKindSupplementary:
		return "Supplementary"
	case VolumeDescriptorKindPartition:
		return "Partition"
	case VolumeDescriptorKindTerminator:
		return "Terminator"
	default:
		return "unknown"
	}
}
func (r BootRecord) BootSystemIdentifierSlice() [32]byte {
	return [32]byte(r[0:32])
}
func (r BootRecord) GetBootSystemIdentifier() [32]byte {
	return [32]byte(r[0:32])
}
func (r *BootRecord) SetBootSystemIdentifier(value [32]byte) {
	copy(r[0:32], value[:])
}
func (r BootRecord) BootIdentifierSlice() [32]byte {
	return [32]byte(r[32:64])
}
func (r BootRecord) GetBootIdentifier() [32]byte {
	return [32]byte(r[32:64])
}
func (r *BootRecord) SetBootIdentifier(value [32]byte) {
	copy(r[32:64], value[:])
}
func (r BootRecord) BootSystemUseSlice() [1977]byte {
	return [1977]byte(r[64:2041])
}
func (r BootRecord) GetBootSystemUse() [1977]uint8 {
	return [1977]uint8(r[64:2041])
}
func (r *BootRecord) SetBootSystemUse(value [1977]uint8) {
	copy(r[64:2041], value[:])
}
func (r BootRecord) Size() int64 {
	return 32 + 32 + 1977
}
func (r BootRecord) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *BootRecord) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type BootRecord [32 + 32 + 1977]byte

func (r VolumeDescriptorSetEndOfVolume) Size() int64 {
	return 0
}
func (r VolumeDescriptorSetEndOfVolume) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *VolumeDescriptorSetEndOfVolume) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type VolumeDescriptorSetEndOfVolume [0]byte

func (r Int16LsbMsb) LsbSlice() [2]byte {
	return [2]byte(r[0:2])
}
func (r Int16LsbMsb) GetLsb() int16 {
	return int16(binary.LittleEndian.Uint16(r[0:2]))
}
func (r *Int16LsbMsb) SetLsb(value int16) {
	binary.LittleEndian.PutUint16(r[0:2], uint16(value))
}
func (r Int16LsbMsb) MsbSlice() [2]byte {
	return [2]byte(r[2:4])
}
func (r Int16LsbMsb) GetMsb() int16 {
	return int16(binary.BigEndian.Uint16(r[2:4]))
}
func (r *Int16LsbMsb) SetMsb(value int16) {
	binary.BigEndian.PutUint16(r[2:4], uint16(value))
}
func (r Int16LsbMsb) Size() int64 {
	return 2 + 2
}
func (r Int16LsbMsb) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *Int16LsbMsb) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type Int16LsbMsb [2 + 2]byte

func (r Int32LsbMsb) LsbSlice() [4]byte {
	return [4]byte(r[0:4])
}
func (r Int32LsbMsb) GetLsb() int32 {
	return int32(binary.LittleEndian.Uint32(r[0:4]))
}
func (r *Int32LsbMsb) SetLsb(value int32) {
	binary.LittleEndian.PutUint32(r[0:4], uint32(value))
}
func (r Int32LsbMsb) MsbSlice() [4]byte {
	return [4]byte(r[4:8])
}
func (r Int32LsbMsb) GetMsb() int32 {
	return int32(binary.BigEndian.Uint32(r[4:8]))
}
func (r *Int32LsbMsb) SetMsb(value int32) {
	binary.BigEndian.PutUint32(r[4:8], uint32(value))
}
func (r Int32LsbMsb) Size() int64 {
	return 4 + 4
}
func (r Int32LsbMsb) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *Int32LsbMsb) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type Int32LsbMsb [4 + 4]byte

func (r DecDatetime) YearSlice() [4]byte {
	return [4]byte(r[0:4])
}
func (r DecDatetime) GetYear() [4]byte {
	return [4]byte(r[0:4])
}
func (r *DecDatetime) SetYear(value [4]byte) {
	copy(r[0:4], value[:])
}
func (r DecDatetime) MonthSlice() [2]byte {
	return [2]byte(r[4:6])
}
func (r DecDatetime) GetMonth() [2]byte {
	return [2]byte(r[4:6])
}
func (r *DecDatetime) SetMonth(value [2]byte) {
	copy(r[4:6], value[:])
}
func (r DecDatetime) DaySlice() [2]byte {
	return [2]byte(r[6:8])
}
func (r DecDatetime) GetDay() [2]byte {
	return [2]byte(r[6:8])
}
func (r *DecDatetime) SetDay(value [2]byte) {
	copy(r[6:8], value[:])
}
func (r DecDatetime) HourSlice() [2]byte {
	return [2]byte(r[8:10])
}
func (r DecDatetime) GetHour() [2]byte {
	return [2]byte(r[8:10])
}
func (r *DecDatetime) SetHour(value [2]byte) {
	copy(r[8:10], value[:])
}
func (r DecDatetime) MinuteSlice() [2]byte {
	return [2]byte(r[10:12])
}
func (r DecDatetime) GetMinute() [2]byte {
	return [2]byte(r[10:12])
}
func (r *DecDatetime) SetMinute(value [2]byte) {
	copy(r[10:12], value[:])
}
func (r DecDatetime) SecondSlice() [2]byte {
	return [2]byte(r[12:14])
}
func (r DecDatetime) GetSecond() [2]byte {
	return [2]byte(r[12:14])
}
func (r *DecDatetime) SetSecond(value [2]byte) {
	copy(r[12:14], value[:])
}
func (r DecDatetime) HundredthsSlice() [2]byte {
	return [2]byte(r[14:16])
}
func (r DecDatetime) GetHundredths() [2]byte {
	return [2]byte(r[14:16])
}
func (r *DecDatetime) SetHundredths(value [2]byte) {
	copy(r[14:16], value[:])
}
func (r DecDatetime) TimezoneOffsetSlice() [1]byte {
	return [1]byte(r[16:17])
}
func (r DecDatetime) GetTimezoneOffset() int8 {
	return int8(r[16:17][0])
}
func (r *DecDatetime) SetTimezoneOffset(value int8) {
	r[16:17][0] = byte(value)
}
func (r DecDatetime) Size() int64 {
	return 4 + 2 + 2 + 2 + 2 + 2 + 2 + 1
}
func (r DecDatetime) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *DecDatetime) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type DecDatetime [4 + 2 + 2 + 2 + 2 + 2 + 2 + 1]byte

func (r DirDatetime) YearSlice() [1]byte {
	return [1]byte(r[0:1])
}
func (r DirDatetime) GetYear() int8 {
	return int8(r[0:1][0])
}
func (r *DirDatetime) SetYear(value int8) {
	r[0:1][0] = byte(value)
}
func (r DirDatetime) MonthSlice() [1]byte {
	return [1]byte(r[1:2])
}
func (r DirDatetime) GetMonth() int8 {
	return int8(r[1:2][0])
}
func (r *DirDatetime) SetMonth(value int8) {
	r[1:2][0] = byte(value)
}
func (r DirDatetime) DaySlice() [1]byte {
	return [1]byte(r[2:3])
}
func (r DirDatetime) GetDay() int8 {
	return int8(r[2:3][0])
}
func (r *DirDatetime) SetDay(value int8) {
	r[2:3][0] = byte(value)
}
func (r DirDatetime) HourSlice() [1]byte {
	return [1]byte(r[3:4])
}
func (r DirDatetime) GetHour() int8 {
	return int8(r[3:4][0])
}
func (r *DirDatetime) SetHour(value int8) {
	r[3:4][0] = byte(value)
}
func (r DirDatetime) MinuteSlice() [1]byte {
	return [1]byte(r[4:5])
}
func (r DirDatetime) GetMinute() int8 {
	return int8(r[4:5][0])
}
func (r *DirDatetime) SetMinute(value int8) {
	r[4:5][0] = byte(value)
}
func (r DirDatetime) SecondSlice() [1]byte {
	return [1]byte(r[5:6])
}
func (r DirDatetime) GetSecond() int8 {
	return int8(r[5:6][0])
}
func (r *DirDatetime) SetSecond(value int8) {
	r[5:6][0] = byte(value)
}
func (r DirDatetime) GmtOffsetSlice() [1]byte {
	return [1]byte(r[6:7])
}
func (r DirDatetime) GetGmtOffset() int8 {
	return int8(r[6:7][0])
}
func (r *DirDatetime) SetGmtOffset(value int8) {
	r[6:7][0] = byte(value)
}
func (r DirDatetime) Size() int64 {
	return 1 + 1 + 1 + 1 + 1 + 1 + 1
}
func (r DirDatetime) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *DirDatetime) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type DirDatetime [1 + 1 + 1 + 1 + 1 + 1 + 1]byte
type DirectoryEntryFlags uint8

const DirectoryEntryFlagsHidden DirectoryEntryFlags = 1
const DirectoryEntryFlagsDirectory DirectoryEntryFlags = 2
const DirectoryEntryFlagsAssociatedFile DirectoryEntryFlags = 4
const DirectoryEntryFlagsHasExtendedAttributeRecord DirectoryEntryFlags = 8
const DirectoryEntryFlagsHasOwnerAndGroup DirectoryEntryFlags = 16
const DirectoryEntryFlagsNotFinalRecordForFile DirectoryEntryFlags = 128

func (b DirectoryEntryFlags) Has(mask DirectoryEntryFlags) bool {
	return b&mask != 0
}
func (r BaseDirectoryEntry) SizeSlice() [1]byte {
	return [1]byte(r[0:1])
}
func (r BaseDirectoryEntry) GetSize() uint8 {
	return uint8(r[0:1][0])
}
func (r *BaseDirectoryEntry) SetSize(value uint8) {
	r[0:1][0] = byte(value)
}
func (r BaseDirectoryEntry) ExtendedAttributeRecordLengthSlice() [1]byte {
	return [1]byte(r[1:2])
}
func (r BaseDirectoryEntry) GetExtendedAttributeRecordLength() uint8 {
	return uint8(r[1:2][0])
}
func (r *BaseDirectoryEntry) SetExtendedAttributeRecordLength(value uint8) {
	r[1:2][0] = byte(value)
}
func (r BaseDirectoryEntry) ExtentLocationSlice() [8]byte {
	return [8]byte(r[2:10])
}
func (r BaseDirectoryEntry) GetExtentLocation() Int32LsbMsb {
	return Int32LsbMsb(r[2:10])
}
func (r *BaseDirectoryEntry) SetExtentLocation(value Int32LsbMsb) {
	copy(r[2:10], value[:])
}
func (r BaseDirectoryEntry) DataLengthSlice() [8]byte {
	return [8]byte(r[10:18])
}
func (r BaseDirectoryEntry) GetDataLength() Int32LsbMsb {
	return Int32LsbMsb(r[10:18])
}
func (r *BaseDirectoryEntry) SetDataLength(value Int32LsbMsb) {
	copy(r[10:18], value[:])
}
func (r BaseDirectoryEntry) DateTimeSlice() [7]byte {
	return [7]byte(r[18:25])
}
func (r BaseDirectoryEntry) GetDateTime() DirDatetime {
	return DirDatetime(r[18:25])
}
func (r *BaseDirectoryEntry) SetDateTime(value DirDatetime) {
	copy(r[18:25], value[:])
}
func (r BaseDirectoryEntry) FlagsSlice() [1]byte {
	return [1]byte(r[25:26])
}
func (r BaseDirectoryEntry) GetFlags() DirectoryEntryFlags {
	return DirectoryEntryFlags(r[25:26][0])
}
func (r *BaseDirectoryEntry) SetFlags(value DirectoryEntryFlags) {
	r[25:26][0] = byte(value)
}
func (r BaseDirectoryEntry) FileUnitSizeSlice() [1]byte {
	return [1]byte(r[26:27])
}
func (r BaseDirectoryEntry) GetFileUnitSize() uint8 {
	return uint8(r[26:27][0])
}
func (r *BaseDirectoryEntry) SetFileUnitSize(value uint8) {
	r[26:27][0] = byte(value)
}
func (r BaseDirectoryEntry) InterleaveGapSlice() [1]byte {
	return [1]byte(r[27:28])
}
func (r BaseDirectoryEntry) GetInterleaveGap() uint8 {
	return uint8(r[27:28][0])
}
func (r *BaseDirectoryEntry) SetInterleaveGap(value uint8) {
	r[27:28][0] = byte(value)
}
func (r BaseDirectoryEntry) VolumeSequenceNumberSlice() [4]byte {
	return [4]byte(r[28:32])
}
func (r BaseDirectoryEntry) GetVolumeSequenceNumber() Int16LsbMsb {
	return Int16LsbMsb(r[28:32])
}
func (r *BaseDirectoryEntry) SetVolumeSequenceNumber(value Int16LsbMsb) {
	copy(r[28:32], value[:])
}
func (r BaseDirectoryEntry) Size() int64 {
	return 1 + 1 + 8 + 8 + 7 + 1 + 1 + 1 + 4
}
func (r BaseDirectoryEntry) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *BaseDirectoryEntry) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type BaseDirectoryEntry [1 + 1 + 8 + 8 + 7 + 1 + 1 + 1 + 4]byte

func (r RootDirectoryEntry) BaseSlice() [32]byte {
	return [32]byte(r[0:32])
}
func (r RootDirectoryEntry) GetBase() BaseDirectoryEntry {
	return BaseDirectoryEntry(r[0:32])
}
func (r *RootDirectoryEntry) SetBase(value BaseDirectoryEntry) {
	copy(r[0:32], value[:])
}
func (r RootDirectoryEntry) FilenameLengthSlice() [1]byte {
	return [1]byte(r[32:33])
}
func (r RootDirectoryEntry) GetFilenameLength() uint8 {
	return uint8(r[32:33][0])
}
func (r *RootDirectoryEntry) SetFilenameLength(value uint8) {
	r[32:33][0] = byte(value)
}
func (r RootDirectoryEntry) Size() int64 {
	return 32 + 1
}
func (r RootDirectoryEntry) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *RootDirectoryEntry) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type RootDirectoryEntry [32 + 1]byte

func (r DynDirectoryEntry) BaseSlice() [32]byte {
	return [32]byte(r[0:32])
}
func (r DynDirectoryEntry) GetBase() BaseDirectoryEntry {
	return BaseDirectoryEntry(r[0:32])
}
func (r DynDirectoryEntry) SetBase(value BaseDirectoryEntry) {
	copy(r[0:32], value[:])
}
func (r DynDirectoryEntry) FilenameLengthSlice() [1]byte {
	return [1]byte(r[32:33])
}
func (r DynDirectoryEntry) GetFilenameLength() uint8 {
	return uint8(r[32:33][0])
}
func (r DynDirectoryEntry) SetFilenameLength(value uint8) {
	r[32:33][0] = byte(value)
}
func (r DynDirectoryEntry) FilenameSlice() []byte {
	return r[33:]
}
func (r DynDirectoryEntry) GetFilename() []byte {
	return []byte(r[33:])
}
func (r DynDirectoryEntry) SetFilename(value []byte) {
	copy(r[33:], value[:])
}

type DynDirectoryEntry []byte

func (r PathTableEntry) SizeSlice() [1]byte {
	return [1]byte(r[0:1])
}
func (r PathTableEntry) GetSize() uint8 {
	return uint8(r[0:1][0])
}
func (r PathTableEntry) SetSize(value uint8) {
	r[0:1][0] = byte(value)
}
func (r PathTableEntry) ExtendedAttributeRecordLengthSlice() [1]byte {
	return [1]byte(r[1:2])
}
func (r PathTableEntry) GetExtendedAttributeRecordLength() uint8 {
	return uint8(r[1:2][0])
}
func (r PathTableEntry) SetExtendedAttributeRecordLength(value uint8) {
	r[1:2][0] = byte(value)
}
func (r PathTableEntry) LocationSlice() [4]byte {
	return [4]byte(r[2:6])
}
func (r PathTableEntry) GetLocation() int32 {
	return int32(binary.LittleEndian.Uint32(r[2:6]))
}
func (r PathTableEntry) SetLocation(value int32) {
	binary.LittleEndian.PutUint32(r[2:6], uint32(value))
}
func (r PathTableEntry) ParentDirectorySlice() [8]byte {
	return [8]byte(r[6:14])
}
func (r PathTableEntry) GetParentDirectory() uint64 {
	return binary.LittleEndian.Uint64(r[6:14])
}
func (r PathTableEntry) SetParentDirectory(value uint64) {
	binary.LittleEndian.PutUint64(r[6:14], value)
}

const PathTableEntryFixedLength = 1 + 1 + 4 + 8

func (r PathTableEntry) NameSlice() []byte {
	return r[14:]
}
func (r PathTableEntry) GetName() []byte {
	return []byte(r[14:])
}
func (r PathTableEntry) SetName(value []byte) {
	copy(r[14:], value[:])
}

type PathTableEntry []byte

func (r PrimaryVolumeDescriptor) SystemIdentifierSlice() [32]byte {
	return [32]byte(r[1:33])
}
func (r PrimaryVolumeDescriptor) GetSystemIdentifier() [32]byte {
	return [32]byte(r[1:33])
}
func (r *PrimaryVolumeDescriptor) SetSystemIdentifier(value [32]byte) {
	copy(r[1:33], value[:])
}
func (r PrimaryVolumeDescriptor) VolumeIdentifierSlice() [32]byte {
	return [32]byte(r[33:65])
}
func (r PrimaryVolumeDescriptor) GetVolumeIdentifier() [32]byte {
	return [32]byte(r[33:65])
}
func (r *PrimaryVolumeDescriptor) SetVolumeIdentifier(value [32]byte) {
	copy(r[33:65], value[:])
}
func (r PrimaryVolumeDescriptor) VolumeSpaceSizeSlice() [8]byte {
	return [8]byte(r[73:81])
}
func (r PrimaryVolumeDescriptor) GetVolumeSpaceSize() Int32LsbMsb {
	return Int32LsbMsb(r[73:81])
}
func (r *PrimaryVolumeDescriptor) SetVolumeSpaceSize(value Int32LsbMsb) {
	copy(r[73:81], value[:])
}
func (r PrimaryVolumeDescriptor) VolumeSetSizeSlice() [4]byte {
	return [4]byte(r[113:117])
}
func (r PrimaryVolumeDescriptor) GetVolumeSetSize() Int16LsbMsb {
	return Int16LsbMsb(r[113:117])
}
func (r *PrimaryVolumeDescriptor) SetVolumeSetSize(value Int16LsbMsb) {
	copy(r[113:117], value[:])
}
func (r PrimaryVolumeDescriptor) VolumeSequenceNumberSlice() [4]byte {
	return [4]byte(r[117:121])
}
func (r PrimaryVolumeDescriptor) GetVolumeSequenceNumber() Int16LsbMsb {
	return Int16LsbMsb(r[117:121])
}
func (r *PrimaryVolumeDescriptor) SetVolumeSequenceNumber(value Int16LsbMsb) {
	copy(r[117:121], value[:])
}
func (r PrimaryVolumeDescriptor) LogicalBlockSizeSlice() [4]byte {
	return [4]byte(r[121:125])
}
func (r PrimaryVolumeDescriptor) GetLogicalBlockSize() Int16LsbMsb {
	return Int16LsbMsb(r[121:125])
}
func (r *PrimaryVolumeDescriptor) SetLogicalBlockSize(value Int16LsbMsb) {
	copy(r[121:125], value[:])
}
func (r PrimaryVolumeDescriptor) PathTableSizeSlice() [8]byte {
	return [8]byte(r[125:133])
}
func (r PrimaryVolumeDescriptor) GetPathTableSize() Int32LsbMsb {
	return Int32LsbMsb(r[125:133])
}
func (r *PrimaryVolumeDescriptor) SetPathTableSize(value Int32LsbMsb) {
	copy(r[125:133], value[:])
}
func (r PrimaryVolumeDescriptor) LocationOfTypeLPathTableSlice() [4]byte {
	return [4]byte(r[133:137])
}
func (r PrimaryVolumeDescriptor) GetLocationOfTypeLPathTable() int32 {
	return int32(binary.LittleEndian.Uint32(r[133:137]))
}
func (r *PrimaryVolumeDescriptor) SetLocationOfTypeLPathTable(value int32) {
	binary.LittleEndian.PutUint32(r[133:137], uint32(value))
}
func (r PrimaryVolumeDescriptor) LocationOfOptionalTypeLPathTableSlice() [4]byte {
	return [4]byte(r[137:141])
}
func (r PrimaryVolumeDescriptor) GetLocationOfOptionalTypeLPathTable() int32 {
	return int32(binary.LittleEndian.Uint32(r[137:141]))
}
func (r *PrimaryVolumeDescriptor) SetLocationOfOptionalTypeLPathTable(value int32) {
	binary.LittleEndian.PutUint32(r[137:141], uint32(value))
}
func (r PrimaryVolumeDescriptor) LocationOfTypeMPathTableSlice() [4]byte {
	return [4]byte(r[141:145])
}
func (r PrimaryVolumeDescriptor) GetLocationOfTypeMPathTable() int32 {
	return int32(binary.BigEndian.Uint32(r[141:145]))
}
func (r *PrimaryVolumeDescriptor) SetLocationOfTypeMPathTable(value int32) {
	binary.BigEndian.PutUint32(r[141:145], uint32(value))
}
func (r PrimaryVolumeDescriptor) LocationOfOptionalTypeMPathTableSlice() [4]byte {
	return [4]byte(r[145:149])
}
func (r PrimaryVolumeDescriptor) GetLocationOfOptionalTypeMPathTable() int32 {
	return int32(binary.BigEndian.Uint32(r[145:149]))
}
func (r *PrimaryVolumeDescriptor) SetLocationOfOptionalTypeMPathTable(value int32) {
	binary.BigEndian.PutUint32(r[145:149], uint32(value))
}
func (r PrimaryVolumeDescriptor) RootDirectoryEntrySlice() [33]byte {
	return [33]byte(r[149:182])
}
func (r PrimaryVolumeDescriptor) GetRootDirectoryEntry() RootDirectoryEntry {
	return RootDirectoryEntry(r[149:182])
}
func (r *PrimaryVolumeDescriptor) SetRootDirectoryEntry(value RootDirectoryEntry) {
	copy(r[149:182], value[:])
}
func (r PrimaryVolumeDescriptor) VolumeSetIdentifierSlice() [128]byte {
	return [128]byte(r[182:310])
}
func (r PrimaryVolumeDescriptor) GetVolumeSetIdentifier() [128]byte {
	return [128]byte(r[182:310])
}
func (r *PrimaryVolumeDescriptor) SetVolumeSetIdentifier(value [128]byte) {
	copy(r[182:310], value[:])
}
func (r PrimaryVolumeDescriptor) PublisherIdentifierSlice() [128]byte {
	return [128]byte(r[310:438])
}
func (r PrimaryVolumeDescriptor) GetPublisherIdentifier() [128]byte {
	return [128]byte(r[310:438])
}
func (r *PrimaryVolumeDescriptor) SetPublisherIdentifier(value [128]byte) {
	copy(r[310:438], value[:])
}
func (r PrimaryVolumeDescriptor) DataPreparerIdentifierSlice() [128]byte {
	return [128]byte(r[438:566])
}
func (r PrimaryVolumeDescriptor) GetDataPreparerIdentifier() [128]byte {
	return [128]byte(r[438:566])
}
func (r *PrimaryVolumeDescriptor) SetDataPreparerIdentifier(value [128]byte) {
	copy(r[438:566], value[:])
}
func (r PrimaryVolumeDescriptor) ApplicationIdentifierSlice() [128]byte {
	return [128]byte(r[566:694])
}
func (r PrimaryVolumeDescriptor) GetApplicationIdentifier() [128]byte {
	return [128]byte(r[566:694])
}
func (r *PrimaryVolumeDescriptor) SetApplicationIdentifier(value [128]byte) {
	copy(r[566:694], value[:])
}
func (r PrimaryVolumeDescriptor) CopyrightFileIdentifierSlice() [37]byte {
	return [37]byte(r[694:731])
}
func (r PrimaryVolumeDescriptor) GetCopyrightFileIdentifier() [37]byte {
	return [37]byte(r[694:731])
}
func (r *PrimaryVolumeDescriptor) SetCopyrightFileIdentifier(value [37]byte) {
	copy(r[694:731], value[:])
}
func (r PrimaryVolumeDescriptor) AbstractFileIdentifierSlice() [37]byte {
	return [37]byte(r[731:768])
}
func (r PrimaryVolumeDescriptor) GetAbstractFileIdentifier() [37]byte {
	return [37]byte(r[731:768])
}
func (r *PrimaryVolumeDescriptor) SetAbstractFileIdentifier(value [37]byte) {
	copy(r[731:768], value[:])
}
func (r PrimaryVolumeDescriptor) BibliographicFileIdentifierSlice() [37]byte {
	return [37]byte(r[768:805])
}
func (r PrimaryVolumeDescriptor) GetBibliographicFileIdentifier() [37]byte {
	return [37]byte(r[768:805])
}
func (r *PrimaryVolumeDescriptor) SetBibliographicFileIdentifier(value [37]byte) {
	copy(r[768:805], value[:])
}
func (r PrimaryVolumeDescriptor) VolumeCreationDateTimeSlice() [17]byte {
	return [17]byte(r[805:822])
}
func (r PrimaryVolumeDescriptor) GetVolumeCreationDateTime() DecDatetime {
	return DecDatetime(r[805:822])
}
func (r *PrimaryVolumeDescriptor) SetVolumeCreationDateTime(value DecDatetime) {
	copy(r[805:822], value[:])
}
func (r PrimaryVolumeDescriptor) VolumeModificationDateTimeSlice() [17]byte {
	return [17]byte(r[822:839])
}
func (r PrimaryVolumeDescriptor) GetVolumeModificationDateTime() DecDatetime {
	return DecDatetime(r[822:839])
}
func (r *PrimaryVolumeDescriptor) SetVolumeModificationDateTime(value DecDatetime) {
	copy(r[822:839], value[:])
}
func (r PrimaryVolumeDescriptor) VolumeExpirationDateTimeSlice() [17]byte {
	return [17]byte(r[839:856])
}
func (r PrimaryVolumeDescriptor) GetVolumeExpirationDateTime() DecDatetime {
	return DecDatetime(r[839:856])
}
func (r *PrimaryVolumeDescriptor) SetVolumeExpirationDateTime(value DecDatetime) {
	copy(r[839:856], value[:])
}
func (r PrimaryVolumeDescriptor) VolumeEffectiveDateTimeSlice() [17]byte {
	return [17]byte(r[856:873])
}
func (r PrimaryVolumeDescriptor) GetVolumeEffectiveDateTime() DecDatetime {
	return DecDatetime(r[856:873])
}
func (r *PrimaryVolumeDescriptor) SetVolumeEffectiveDateTime(value DecDatetime) {
	copy(r[856:873], value[:])
}
func (r PrimaryVolumeDescriptor) FileStructureVersionSlice() [1]byte {
	return [1]byte(r[873:874])
}
func (r PrimaryVolumeDescriptor) GetFileStructureVersion() uint8 {
	return uint8(r[873:874][0])
}
func (r *PrimaryVolumeDescriptor) SetFileStructureVersion(value uint8) {
	r[873:874][0] = byte(value)
}
func (r PrimaryVolumeDescriptor) ApplicationUsedSlice() [512]byte {
	return [512]byte(r[875:1387])
}
func (r PrimaryVolumeDescriptor) GetApplicationUsed() [512]uint8 {
	return [512]uint8(r[875:1387])
}
func (r *PrimaryVolumeDescriptor) SetApplicationUsed(value [512]uint8) {
	copy(r[875:1387], value[:])
}
func (r PrimaryVolumeDescriptor) Size() int64 {
	return 1 + 32 + 32 + 8 + 8 + 32 + 4 + 4 + 4 + 8 + 4 + 4 + 4 + 4 + 33 + 128 + 128 + 128 + 128 + 37 + 37 + 37 + 17 + 17 + 17 + 17 + 1 + 1 + 512 + 653
}
func (r PrimaryVolumeDescriptor) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *PrimaryVolumeDescriptor) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type PrimaryVolumeDescriptor [1 + 32 + 32 + 8 + 8 + 32 + 4 + 4 + 4 + 8 + 4 + 4 + 4 + 4 + 33 + 128 + 128 + 128 + 128 + 37 + 37 + 37 + 17 + 17 + 17 + 17 + 1 + 1 + 512 + 653]byte

func (r VolumeDescriptorSetTerminator) Size() int64 {
	return 0
}
func (r VolumeDescriptorSetTerminator) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *VolumeDescriptorSetTerminator) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type VolumeDescriptorSetTerminator [0]byte

func (u VolumeDescriptorContent) GetRawBytes() [2041]uint8 {
	return [2041]uint8(u[:])
}
func (u VolumeDescriptorContent) SetRawBytes(value [2041]uint8) {
	copy(u[:], value[:])
}
func (u VolumeDescriptorContent) GetBootRecord() BootRecord {
	return BootRecord(u[:])
}
func (u VolumeDescriptorContent) SetBootRecord(value BootRecord) {
	copy(u[:], value[:])
}
func (u VolumeDescriptorContent) GetPrimaryVolumeDescriptor() PrimaryVolumeDescriptor {
	return PrimaryVolumeDescriptor(u[:])
}
func (u VolumeDescriptorContent) SetPrimaryVolumeDescriptor(value PrimaryVolumeDescriptor) {
	copy(u[:], value[:])
}
func (u VolumeDescriptorContent) GetVolumeDescriptorSetTerminator() VolumeDescriptorSetTerminator {
	return VolumeDescriptorSetTerminator(u[:])
}
func (u VolumeDescriptorContent) SetVolumeDescriptorSetTerminator(value VolumeDescriptorSetTerminator) {
	copy(u[:], value[:])
}

type VolumeDescriptorContent [2041]byte

func (r VolumeDescriptor) KindSlice() [1]byte {
	return [1]byte(r[0:1])
}
func (r VolumeDescriptor) GetKind() VolumeDescriptorKind {
	return VolumeDescriptorKind(r[0:1][0])
}
func (r *VolumeDescriptor) SetKind(value VolumeDescriptorKind) {
	r[0:1][0] = byte(value)
}
func (r VolumeDescriptor) IdentifierSlice() [5]byte {
	return [5]byte(r[1:6])
}
func (r VolumeDescriptor) GetIdentifier() [5]uint8 {
	return [5]uint8(r[1:6])
}
func (r *VolumeDescriptor) SetIdentifier(value [5]uint8) {
	copy(r[1:6], value[:])
}
func (r VolumeDescriptor) VersionSlice() [1]byte {
	return [1]byte(r[6:7])
}
func (r VolumeDescriptor) GetVersion() uint8 {
	return uint8(r[6:7][0])
}
func (r *VolumeDescriptor) SetVersion(value uint8) {
	r[6:7][0] = byte(value)
}
func (r VolumeDescriptor) ContentsSlice() [2041]byte {
	return [2041]byte(r[7:2048])
}
func (r VolumeDescriptor) GetContents() VolumeDescriptorContent {
	return VolumeDescriptorContent(r[7:2048])
}
func (r *VolumeDescriptor) SetContents(value VolumeDescriptorContent) {
	copy(r[7:2048], value[:])
}
func (r VolumeDescriptor) Size() int64 {
	return 1 + 5 + 1 + 2041
}
func (r VolumeDescriptor) ReadAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(buf, r[off:]), nil
}
func (r *VolumeDescriptor) WriteAt(buf []byte, off int64) (int, error) {
	if off > r.Size() {
		return 0, io.EOF
	}
	return copy(r[off:], buf), nil
}

type VolumeDescriptor [1 + 5 + 1 + 2041]byte
