// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------------
// BuildDefinition reference
// ----------------------
// In Go, BuildDefinition is an interface. Here we represent it as an indirect
// typed hash reference (string). Replace with a stronger type if needed.
type BuildDefinitionRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // Indirect reference to a BuildDefinition
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildDefinitionRef) Reset() {
	*x = BuildDefinitionRef{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildDefinitionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildDefinitionRef) ProtoMessage() {}

func (x *BuildDefinitionRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildDefinitionRef.ProtoReflect.Descriptor instead.
func (*BuildDefinitionRef) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *BuildDefinitionRef) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// Package query used in plans.
type PackageQuery struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MatchDirect      bool                   `protobuf:"varint,1,opt,name=match_direct,json=matchDirect,proto3" json:"match_direct,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MatchPartialName bool                   `protobuf:"varint,3,opt,name=match_partial_name,json=matchPartialName,proto3" json:"match_partial_name,omitempty"`
	Version          string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Tags             []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PackageQuery) Reset() {
	*x = PackageQuery{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageQuery) ProtoMessage() {}

func (x *PackageQuery) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageQuery.ProtoReflect.Descriptor instead.
func (*PackageQuery) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *PackageQuery) GetMatchDirect() bool {
	if x != nil {
		return x.MatchDirect
	}
	return false
}

func (x *PackageQuery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageQuery) GetMatchPartialName() bool {
	if x != nil {
		return x.MatchPartialName
	}
	return false
}

func (x *PackageQuery) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackageQuery) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SerializableValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializableValue) Reset() {
	*x = SerializableValue{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializableValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializableValue) ProtoMessage() {}

func (x *SerializableValue) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializableValue.ProtoReflect.Descriptor instead.
func (*SerializableValue) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x05proto\"(\n" +
	"\x12BuildDefinitionRef\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\xa1\x01\n" +
	"\fPackageQuery\x12!\n" +
	"\fmatch_direct\x18\x01 \x01(\bR\vmatchDirect\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x12match_partial_name\x18\x03 \x01(\bR\x10matchPartialName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"\x13\n" +
	"\x11SerializableValue\"\x06\n" +
	"\x04Fileb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_goTypes = []any{
	(*BuildDefinitionRef)(nil), // 0: proto.BuildDefinitionRef
	(*PackageQuery)(nil),       // 1: proto.PackageQuery
	(*SerializableValue)(nil),  // 2: proto.SerializableValue
	(*File)(nil),               // 3: proto.File
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
