// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: definition.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------------
// BuildDefinition
// ----------------------
// A BuildDefinition is a polymorphic type that can represent any of the
// builder parameter messages. In Go this is an interface; here it is a oneof.
type BuildDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Definition:
	//
	//	*BuildDefinition_BuildFs
	//	*BuildDefinition_BuildVm
	//	*BuildDefinition_BuildEmulator
	//	*BuildDefinition_DecompressFile
	//	*BuildDefinition_FetchHttp
	//	*BuildDefinition_RegistryRequest
	//	*BuildDefinition_FetchOciImage
	//	*BuildDefinition_FetchCvmfs
	//	*BuildDefinition_ReadOciImage
	//	*BuildDefinition_File
	//	*BuildDefinition_ConstantHash
	//	*BuildDefinition_ExtractFile
	//	*BuildDefinition_Plan
	//	*BuildDefinition_ReadArchive
	//	*BuildDefinition_Star
	Definition    isBuildDefinition_Definition `protobuf_oneof:"definition"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildDefinition) Reset() {
	*x = BuildDefinition{}
	mi := &file_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildDefinition) ProtoMessage() {}

func (x *BuildDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildDefinition.ProtoReflect.Descriptor instead.
func (*BuildDefinition) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{0}
}

func (x *BuildDefinition) GetDefinition() isBuildDefinition_Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *BuildDefinition) GetBuildFs() *BuildFsParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_BuildFs); ok {
			return x.BuildFs
		}
	}
	return nil
}

func (x *BuildDefinition) GetBuildVm() *BuildVmParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_BuildVm); ok {
			return x.BuildVm
		}
	}
	return nil
}

func (x *BuildDefinition) GetBuildEmulator() *BuildEmulatorParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_BuildEmulator); ok {
			return x.BuildEmulator
		}
	}
	return nil
}

func (x *BuildDefinition) GetDecompressFile() *DecompressFileParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_DecompressFile); ok {
			return x.DecompressFile
		}
	}
	return nil
}

func (x *BuildDefinition) GetFetchHttp() *FetchHttpParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_FetchHttp); ok {
			return x.FetchHttp
		}
	}
	return nil
}

func (x *BuildDefinition) GetRegistryRequest() *RegistryRequestParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_RegistryRequest); ok {
			return x.RegistryRequest
		}
	}
	return nil
}

func (x *BuildDefinition) GetFetchOciImage() *FetchOciImageParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_FetchOciImage); ok {
			return x.FetchOciImage
		}
	}
	return nil
}

func (x *BuildDefinition) GetFetchCvmfs() *FetchCVMFSParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_FetchCvmfs); ok {
			return x.FetchCvmfs
		}
	}
	return nil
}

func (x *BuildDefinition) GetReadOciImage() *ReadOciImageParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_ReadOciImage); ok {
			return x.ReadOciImage
		}
	}
	return nil
}

func (x *BuildDefinition) GetFile() *FileParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *BuildDefinition) GetConstantHash() *ConstantHashParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_ConstantHash); ok {
			return x.ConstantHash
		}
	}
	return nil
}

func (x *BuildDefinition) GetExtractFile() *ExtractFileParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_ExtractFile); ok {
			return x.ExtractFile
		}
	}
	return nil
}

func (x *BuildDefinition) GetPlan() *PlanParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_Plan); ok {
			return x.Plan
		}
	}
	return nil
}

func (x *BuildDefinition) GetReadArchive() *ReadArchiveParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_ReadArchive); ok {
			return x.ReadArchive
		}
	}
	return nil
}

func (x *BuildDefinition) GetStar() *StarParameters {
	if x != nil {
		if x, ok := x.Definition.(*BuildDefinition_Star); ok {
			return x.Star
		}
	}
	return nil
}

type isBuildDefinition_Definition interface {
	isBuildDefinition_Definition()
}

type BuildDefinition_BuildFs struct {
	BuildFs *BuildFsParameters `protobuf:"bytes,1,opt,name=build_fs,json=buildFs,proto3,oneof"`
}

type BuildDefinition_BuildVm struct {
	BuildVm *BuildVmParameters `protobuf:"bytes,2,opt,name=build_vm,json=buildVm,proto3,oneof"`
}

type BuildDefinition_BuildEmulator struct {
	BuildEmulator *BuildEmulatorParameters `protobuf:"bytes,3,opt,name=build_emulator,json=buildEmulator,proto3,oneof"`
}

type BuildDefinition_DecompressFile struct {
	DecompressFile *DecompressFileParameters `protobuf:"bytes,4,opt,name=decompress_file,json=decompressFile,proto3,oneof"`
}

type BuildDefinition_FetchHttp struct {
	FetchHttp *FetchHttpParameters `protobuf:"bytes,5,opt,name=fetch_http,json=fetchHttp,proto3,oneof"`
}

type BuildDefinition_RegistryRequest struct {
	RegistryRequest *RegistryRequestParameters `protobuf:"bytes,6,opt,name=registry_request,json=registryRequest,proto3,oneof"`
}

type BuildDefinition_FetchOciImage struct {
	FetchOciImage *FetchOciImageParameters `protobuf:"bytes,7,opt,name=fetch_oci_image,json=fetchOciImage,proto3,oneof"`
}

type BuildDefinition_FetchCvmfs struct {
	FetchCvmfs *FetchCVMFSParameters `protobuf:"bytes,8,opt,name=fetch_cvmfs,json=fetchCvmfs,proto3,oneof"`
}

type BuildDefinition_ReadOciImage struct {
	ReadOciImage *ReadOciImageParameters `protobuf:"bytes,9,opt,name=read_oci_image,json=readOciImage,proto3,oneof"`
}

type BuildDefinition_File struct {
	File *FileParameters `protobuf:"bytes,10,opt,name=file,proto3,oneof"`
}

type BuildDefinition_ConstantHash struct {
	ConstantHash *ConstantHashParameters `protobuf:"bytes,11,opt,name=constant_hash,json=constantHash,proto3,oneof"`
}

type BuildDefinition_ExtractFile struct {
	ExtractFile *ExtractFileParameters `protobuf:"bytes,12,opt,name=extract_file,json=extractFile,proto3,oneof"`
}

type BuildDefinition_Plan struct {
	Plan *PlanParameters `protobuf:"bytes,13,opt,name=plan,proto3,oneof"`
}

type BuildDefinition_ReadArchive struct {
	ReadArchive *ReadArchiveParameters `protobuf:"bytes,14,opt,name=read_archive,json=readArchive,proto3,oneof"`
}

type BuildDefinition_Star struct {
	Star *StarParameters `protobuf:"bytes,15,opt,name=star,proto3,oneof"`
}

func (*BuildDefinition_BuildFs) isBuildDefinition_Definition() {}

func (*BuildDefinition_BuildVm) isBuildDefinition_Definition() {}

func (*BuildDefinition_BuildEmulator) isBuildDefinition_Definition() {}

func (*BuildDefinition_DecompressFile) isBuildDefinition_Definition() {}

func (*BuildDefinition_FetchHttp) isBuildDefinition_Definition() {}

func (*BuildDefinition_RegistryRequest) isBuildDefinition_Definition() {}

func (*BuildDefinition_FetchOciImage) isBuildDefinition_Definition() {}

func (*BuildDefinition_FetchCvmfs) isBuildDefinition_Definition() {}

func (*BuildDefinition_ReadOciImage) isBuildDefinition_Definition() {}

func (*BuildDefinition_File) isBuildDefinition_Definition() {}

func (*BuildDefinition_ConstantHash) isBuildDefinition_Definition() {}

func (*BuildDefinition_ExtractFile) isBuildDefinition_Definition() {}

func (*BuildDefinition_Plan) isBuildDefinition_Definition() {}

func (*BuildDefinition_ReadArchive) isBuildDefinition_Definition() {}

func (*BuildDefinition_Star) isBuildDefinition_Definition() {}

// Build Filesystem exports a series of directives into a filesystem format.
// The build result is the built filesystem.
type BuildFsParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directives    []*Directive           `protobuf:"bytes,1,rep,name=directives,proto3" json:"directives,omitempty"` // A list of directives to build the filesystem from.
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`             // The kind of filesystem to create (initramfs, tar, fragments).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildFsParameters) Reset() {
	*x = BuildFsParameters{}
	mi := &file_definition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildFsParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFsParameters) ProtoMessage() {}

func (x *BuildFsParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFsParameters.ProtoReflect.Descriptor instead.
func (*BuildFsParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{1}
}

func (x *BuildFsParameters) GetDirectives() []*Directive {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *BuildFsParameters) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// Build Virtual Machine uses TinyRange to run a virtual machine with a root
// filesystem provided by a list of directives.
// The output is either nothing or a file from the virtual machine.
type BuildVmParameters struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Directives       []*Directive           `protobuf:"bytes,1,rep,name=directives,proto3" json:"directives,omitempty"`                                     // A list of directives to build the root filesystem from.
	OutputFile       string                 `protobuf:"bytes,2,opt,name=output_file,json=outputFile,proto3" json:"output_file,omitempty"`                   // The name inside of the guest of the file to copy as the build result.
	Architecture     string                 `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`                                 // The CPU Architecture of the guest. If null defaults to the host architecture.
	RootArchitecture string                 `protobuf:"bytes,4,opt,name=root_architecture,json=rootArchitecture,proto3" json:"root_architecture,omitempty"` // The CPU Architecture of the root filesystem. This is a hint to enable vmm-specific optimizations.
	Kernel           *BuildDefinitionRef    `protobuf:"bytes,5,opt,name=kernel,proto3" json:"kernel,omitempty"`                                             // A build definition that creates the kernel.
	InitRamFs        *BuildDefinitionRef    `protobuf:"bytes,6,opt,name=init_ram_fs,json=initRamFs,proto3" json:"init_ram_fs,omitempty"`                    // A build definition that creates the initial ram filesystem.
	CpuCores         int32                  `protobuf:"varint,7,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`                        // The number of CPU cores to allocate to the virtual machine.
	MemoryMb         int32                  `protobuf:"varint,8,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`                        // The amount of RAM in the virtual machine in megabytes.
	AutoScale        bool                   `protobuf:"varint,9,opt,name=auto_scale,json=autoScale,proto3" json:"auto_scale,omitempty"`                     // Automatically scale the CPU and RAM to the limits of the host.
	StorageSize      int32                  `protobuf:"varint,10,opt,name=storage_size,json=storageSize,proto3" json:"storage_size,omitempty"`              // The amount of storage the root device will have in megabytes.
	Interaction      string                 `protobuf:"bytes,11,opt,name=interaction,proto3" json:"interaction,omitempty"`                                  // How will the virtual machine be interacted with (ssh, serial).
	HistoryKey       string                 `protobuf:"bytes,12,opt,name=history_key,json=historyKey,proto3" json:"history_key,omitempty"`                  // The key used to store the history of the VM. If empty no history is stored.
	Debug            bool                   `protobuf:"varint,13,opt,name=debug,proto3" json:"debug,omitempty"`                                             // Redirect hypervisor input to the host. The VM will exit after it completes initialization.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BuildVmParameters) Reset() {
	*x = BuildVmParameters{}
	mi := &file_definition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildVmParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildVmParameters) ProtoMessage() {}

func (x *BuildVmParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildVmParameters.ProtoReflect.Descriptor instead.
func (*BuildVmParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{2}
}

func (x *BuildVmParameters) GetDirectives() []*Directive {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *BuildVmParameters) GetOutputFile() string {
	if x != nil {
		return x.OutputFile
	}
	return ""
}

func (x *BuildVmParameters) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *BuildVmParameters) GetRootArchitecture() string {
	if x != nil {
		return x.RootArchitecture
	}
	return ""
}

func (x *BuildVmParameters) GetKernel() *BuildDefinitionRef {
	if x != nil {
		return x.Kernel
	}
	return nil
}

func (x *BuildVmParameters) GetInitRamFs() *BuildDefinitionRef {
	if x != nil {
		return x.InitRamFs
	}
	return nil
}

func (x *BuildVmParameters) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *BuildVmParameters) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *BuildVmParameters) GetAutoScale() bool {
	if x != nil {
		return x.AutoScale
	}
	return false
}

func (x *BuildVmParameters) GetStorageSize() int32 {
	if x != nil {
		return x.StorageSize
	}
	return 0
}

func (x *BuildVmParameters) GetInteraction() string {
	if x != nil {
		return x.Interaction
	}
	return ""
}

func (x *BuildVmParameters) GetHistoryKey() string {
	if x != nil {
		return x.HistoryKey
	}
	return ""
}

func (x *BuildVmParameters) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

// Build Emulator uses an internal shell emulator to run simple shell scripts
// with support from Starlark to stub applications. The Directives and output
// file work the same way as BuildVmParameters.
type BuildEmulatorParameters struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Directives     []*Directive           `protobuf:"bytes,1,rep,name=directives,proto3" json:"directives,omitempty"`                               // A list of directives to build the root filesystem from.
	OutputFile     string                 `protobuf:"bytes,2,opt,name=output_file,json=outputFile,proto3" json:"output_file,omitempty"`             // The name inside of the guest of the file to copy as the build result.
	ScriptFilename string                 `protobuf:"bytes,3,opt,name=script_filename,json=scriptFilename,proto3" json:"script_filename,omitempty"` // The filename of the script used to run this builder.
	CreateName     string                 `protobuf:"bytes,4,opt,name=create_name,json=createName,proto3" json:"create_name,omitempty"`             // The name of the create function.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuildEmulatorParameters) Reset() {
	*x = BuildEmulatorParameters{}
	mi := &file_definition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEmulatorParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEmulatorParameters) ProtoMessage() {}

func (x *BuildEmulatorParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEmulatorParameters.ProtoReflect.Descriptor instead.
func (*BuildEmulatorParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{3}
}

func (x *BuildEmulatorParameters) GetDirectives() []*Directive {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *BuildEmulatorParameters) GetOutputFile() string {
	if x != nil {
		return x.OutputFile
	}
	return ""
}

func (x *BuildEmulatorParameters) GetScriptFilename() string {
	if x != nil {
		return x.ScriptFilename
	}
	return ""
}

func (x *BuildEmulatorParameters) GetCreateName() string {
	if x != nil {
		return x.CreateName
	}
	return ""
}

// Decompress a build result.
type DecompressFileParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BuildDefinitionRef    `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"` // The build result to decompress.
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // The compression format to use (.xz).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecompressFileParameters) Reset() {
	*x = DecompressFileParameters{}
	mi := &file_definition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecompressFileParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecompressFileParameters) ProtoMessage() {}

func (x *DecompressFileParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecompressFileParameters.ProtoReflect.Descriptor instead.
func (*DecompressFileParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{4}
}

func (x *DecompressFileParameters) GetBase() *BuildDefinitionRef {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DecompressFileParameters) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// Download a file from the internet.
type FetchHttpParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                                                                                   // The URL to download (can start with mirror:// if a mirror is registered).
	ExpireTime    int64                  `protobuf:"varint,2,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`                                                  // How long before the file is considered expired and will be redownloaded.
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // A collection of headers to send along with the request.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchHttpParameters) Reset() {
	*x = FetchHttpParameters{}
	mi := &file_definition_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchHttpParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchHttpParameters) ProtoMessage() {}

func (x *FetchHttpParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchHttpParameters.ProtoReflect.Descriptor instead.
func (*FetchHttpParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{5}
}

func (x *FetchHttpParameters) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchHttpParameters) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *FetchHttpParameters) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// Make a request to an OCI registry.
// This is an internal type that is attached to a context to persist the authentication token between requests.
type RegistryRequestParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,2,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	Accept        []string               `protobuf:"bytes,3,rep,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRequestParameters) Reset() {
	*x = RegistryRequestParameters{}
	mi := &file_definition_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRequestParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRequestParameters) ProtoMessage() {}

func (x *RegistryRequestParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRequestParameters.ProtoReflect.Descriptor instead.
func (*RegistryRequestParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{6}
}

func (x *RegistryRequestParameters) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RegistryRequestParameters) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *RegistryRequestParameters) GetAccept() []string {
	if x != nil {
		return x.Accept
	}
	return nil
}

// Download an image from an OCI registry.
// The output is a serialized copy of FetchOciImageDefinition.
type FetchOciImageParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registry      string                 `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Architecture  string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOciImageParameters) Reset() {
	*x = FetchOciImageParameters{}
	mi := &file_definition_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOciImageParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOciImageParameters) ProtoMessage() {}

func (x *FetchOciImageParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOciImageParameters.ProtoReflect.Descriptor instead.
func (*FetchOciImageParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{7}
}

func (x *FetchOciImageParameters) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *FetchOciImageParameters) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *FetchOciImageParameters) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *FetchOciImageParameters) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

// Create a streaming archive from a CernVM-FS filesystem.
// The output is an archive2 file.
type FetchCVMFSParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mirror        string                 `protobuf:"bytes,1,opt,name=mirror,proto3" json:"mirror,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchCVMFSParameters) Reset() {
	*x = FetchCVMFSParameters{}
	mi := &file_definition_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCVMFSParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCVMFSParameters) ProtoMessage() {}

func (x *FetchCVMFSParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCVMFSParameters.ProtoReflect.Descriptor instead.
func (*FetchCVMFSParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{8}
}

func (x *FetchCVMFSParameters) GetMirror() string {
	if x != nil {
		return x.Mirror
	}
	return ""
}

func (x *FetchCVMFSParameters) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *FetchCVMFSParameters) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Read an OCI image from a file.
// The output is a serialized copy of FetchOciImageDefinition (for compatibility reasons).
type ReadOciImageParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BuildDefinitionRef    `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOciImageParameters) Reset() {
	*x = ReadOciImageParameters{}
	mi := &file_definition_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOciImageParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOciImageParameters) ProtoMessage() {}

func (x *ReadOciImageParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOciImageParameters.ProtoReflect.Descriptor instead.
func (*ReadOciImageParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{9}
}

func (x *ReadOciImageParameters) GetBase() *BuildDefinitionRef {
	if x != nil {
		return x.Base
	}
	return nil
}

// Copy a file to the build output directory.
type FileParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileParameters) Reset() {
	*x = FileParameters{}
	mi := &file_definition_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileParameters) ProtoMessage() {}

func (x *FileParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileParameters.ProtoReflect.Descriptor instead.
func (*FileParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{10}
}

func (x *FileParameters) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

// Constant hash needs to be manually replicated by constructing an object.
type ConstantHashParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConstantHashParameters) Reset() {
	*x = ConstantHashParameters{}
	mi := &file_definition_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConstantHashParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstantHashParameters) ProtoMessage() {}

func (x *ConstantHashParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstantHashParameters.ProtoReflect.Descriptor instead.
func (*ConstantHashParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{11}
}

func (x *ConstantHashParameters) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// Extract a single file from an archive.
type ExtractFileParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BuildDefinitionRef    `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractFileParameters) Reset() {
	*x = ExtractFileParameters{}
	mi := &file_definition_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractFileParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractFileParameters) ProtoMessage() {}

func (x *ExtractFileParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractFileParameters.ProtoReflect.Descriptor instead.
func (*ExtractFileParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{12}
}

func (x *ExtractFileParameters) GetBase() *BuildDefinitionRef {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ExtractFileParameters) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Create an installation plan using a given builder.
// The result is a serialized version of PlanDefinition which contains a list of fragments.
type PlanParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builder       string                 `protobuf:"bytes,1,opt,name=builder,proto3" json:"builder,omitempty"`                // A registered builder to use to create the installation plan.
	Architecture  string                 `protobuf:"bytes,2,opt,name=architecture,proto3" json:"architecture,omitempty"`      // A CPUArchitecture. If not specified then use the host architecture.
	Search        []*PackageQuery        `protobuf:"bytes,3,rep,name=search,proto3" json:"search,omitempty"`                  // A list of packages to query to make the installation plan.
	TagList       []string               `protobuf:"bytes,4,rep,name=tag_list,json=tagList,proto3" json:"tag_list,omitempty"` // A list of tags used to modify and configure the plan.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanParameters) Reset() {
	*x = PlanParameters{}
	mi := &file_definition_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanParameters) ProtoMessage() {}

func (x *PlanParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanParameters.ProtoReflect.Descriptor instead.
func (*PlanParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{13}
}

func (x *PlanParameters) GetBuilder() string {
	if x != nil {
		return x.Builder
	}
	return ""
}

func (x *PlanParameters) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *PlanParameters) GetSearch() []*PackageQuery {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *PlanParameters) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

// Read an archive in a compressed format.
// The output is a file in the native archive format (it still has to be read with ReadArchiveFromFile).
type ReadArchiveParameters struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Base            *BuildDefinitionRef    `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                               // The definition used as a base.
	Kind            string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`                                               // The compression kind of the input file (supports .gz, .zst, and .xz compression and .tar, .cpio, and .ar archive formats).
	StripComponents int32                  `protobuf:"varint,3,opt,name=strip_components,json=stripComponents,proto3" json:"strip_components,omitempty"` // The number of components to strip from the path.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadArchiveParameters) Reset() {
	*x = ReadArchiveParameters{}
	mi := &file_definition_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArchiveParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArchiveParameters) ProtoMessage() {}

func (x *ReadArchiveParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArchiveParameters.ProtoReflect.Descriptor instead.
func (*ReadArchiveParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{14}
}

func (x *ReadArchiveParameters) GetBase() *BuildDefinitionRef {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ReadArchiveParameters) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ReadArchiveParameters) GetStripComponents() int32 {
	if x != nil {
		return x.StripComponents
	}
	return 0
}

// Execute a builder defined in Starlark.
type StarParameters struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScriptFilename string                 `protobuf:"bytes,1,opt,name=script_filename,json=scriptFilename,proto3" json:"script_filename,omitempty"` // The filename of the script used to run this builder.
	BuilderName    string                 `protobuf:"bytes,2,opt,name=builder_name,json=builderName,proto3" json:"builder_name,omitempty"`          // The name of the builder function.
	Arguments      []*SerializableValue   `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`                                 // The arguments passed to the function. These must be convertible to starlark.Value.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StarParameters) Reset() {
	*x = StarParameters{}
	mi := &file_definition_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarParameters) ProtoMessage() {}

func (x *StarParameters) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarParameters.ProtoReflect.Descriptor instead.
func (*StarParameters) Descriptor() ([]byte, []int) {
	return file_definition_proto_rawDescGZIP(), []int{15}
}

func (x *StarParameters) GetScriptFilename() string {
	if x != nil {
		return x.ScriptFilename
	}
	return ""
}

func (x *StarParameters) GetBuilderName() string {
	if x != nil {
		return x.BuilderName
	}
	return ""
}

func (x *StarParameters) GetArguments() []*SerializableValue {
	if x != nil {
		return x.Arguments
	}
	return nil
}

var File_definition_proto protoreflect.FileDescriptor

const file_definition_proto_rawDesc = "" +
	"\n" +
	"\x10definition.proto\x12\x05proto\x1a\fcommon.proto\x1a\x0fdirective.proto\"\xd2\a\n" +
	"\x0fBuildDefinition\x125\n" +
	"\bbuild_fs\x18\x01 \x01(\v2\x18.proto.BuildFsParametersH\x00R\abuildFs\x125\n" +
	"\bbuild_vm\x18\x02 \x01(\v2\x18.proto.BuildVmParametersH\x00R\abuildVm\x12G\n" +
	"\x0ebuild_emulator\x18\x03 \x01(\v2\x1e.proto.BuildEmulatorParametersH\x00R\rbuildEmulator\x12J\n" +
	"\x0fdecompress_file\x18\x04 \x01(\v2\x1f.proto.DecompressFileParametersH\x00R\x0edecompressFile\x12;\n" +
	"\n" +
	"fetch_http\x18\x05 \x01(\v2\x1a.proto.FetchHttpParametersH\x00R\tfetchHttp\x12M\n" +
	"\x10registry_request\x18\x06 \x01(\v2 .proto.RegistryRequestParametersH\x00R\x0fregistryRequest\x12H\n" +
	"\x0ffetch_oci_image\x18\a \x01(\v2\x1e.proto.FetchOciImageParametersH\x00R\rfetchOciImage\x12>\n" +
	"\vfetch_cvmfs\x18\b \x01(\v2\x1b.proto.FetchCVMFSParametersH\x00R\n" +
	"fetchCvmfs\x12E\n" +
	"\x0eread_oci_image\x18\t \x01(\v2\x1d.proto.ReadOciImageParametersH\x00R\freadOciImage\x12+\n" +
	"\x04file\x18\n" +
	" \x01(\v2\x15.proto.FileParametersH\x00R\x04file\x12D\n" +
	"\rconstant_hash\x18\v \x01(\v2\x1d.proto.ConstantHashParametersH\x00R\fconstantHash\x12A\n" +
	"\fextract_file\x18\f \x01(\v2\x1c.proto.ExtractFileParametersH\x00R\vextractFile\x12+\n" +
	"\x04plan\x18\r \x01(\v2\x15.proto.PlanParametersH\x00R\x04plan\x12A\n" +
	"\fread_archive\x18\x0e \x01(\v2\x1c.proto.ReadArchiveParametersH\x00R\vreadArchive\x12+\n" +
	"\x04star\x18\x0f \x01(\v2\x15.proto.StarParametersH\x00R\x04starB\f\n" +
	"\n" +
	"definition\"Y\n" +
	"\x11BuildFsParameters\x120\n" +
	"\n" +
	"directives\x18\x01 \x03(\v2\x10.proto.DirectiveR\n" +
	"directives\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"\xfa\x03\n" +
	"\x11BuildVmParameters\x120\n" +
	"\n" +
	"directives\x18\x01 \x03(\v2\x10.proto.DirectiveR\n" +
	"directives\x12\x1f\n" +
	"\voutput_file\x18\x02 \x01(\tR\n" +
	"outputFile\x12\"\n" +
	"\farchitecture\x18\x03 \x01(\tR\farchitecture\x12+\n" +
	"\x11root_architecture\x18\x04 \x01(\tR\x10rootArchitecture\x121\n" +
	"\x06kernel\x18\x05 \x01(\v2\x19.proto.BuildDefinitionRefR\x06kernel\x129\n" +
	"\vinit_ram_fs\x18\x06 \x01(\v2\x19.proto.BuildDefinitionRefR\tinitRamFs\x12\x1b\n" +
	"\tcpu_cores\x18\a \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\b \x01(\x05R\bmemoryMb\x12\x1d\n" +
	"\n" +
	"auto_scale\x18\t \x01(\bR\tautoScale\x12!\n" +
	"\fstorage_size\x18\n" +
	" \x01(\x05R\vstorageSize\x12 \n" +
	"\vinteraction\x18\v \x01(\tR\vinteraction\x12\x1f\n" +
	"\vhistory_key\x18\f \x01(\tR\n" +
	"historyKey\x12\x14\n" +
	"\x05debug\x18\r \x01(\bR\x05debug\"\xb6\x01\n" +
	"\x17BuildEmulatorParameters\x120\n" +
	"\n" +
	"directives\x18\x01 \x03(\v2\x10.proto.DirectiveR\n" +
	"directives\x12\x1f\n" +
	"\voutput_file\x18\x02 \x01(\tR\n" +
	"outputFile\x12'\n" +
	"\x0fscript_filename\x18\x03 \x01(\tR\x0escriptFilename\x12\x1f\n" +
	"\vcreate_name\x18\x04 \x01(\tR\n" +
	"createName\"]\n" +
	"\x18DecompressFileParameters\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.proto.BuildDefinitionRefR\x04base\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"\xc7\x01\n" +
	"\x13FetchHttpParameters\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1f\n" +
	"\vexpire_time\x18\x02 \x01(\x03R\n" +
	"expireTime\x12A\n" +
	"\aheaders\x18\x03 \x03(\v2'.proto.FetchHttpParameters.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x19RegistryRequestParameters\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1f\n" +
	"\vexpire_time\x18\x02 \x01(\x03R\n" +
	"expireTime\x12\x16\n" +
	"\x06accept\x18\x03 \x03(\tR\x06accept\"\x81\x01\n" +
	"\x17FetchOciImageParameters\x12\x1a\n" +
	"\bregistry\x18\x01 \x01(\tR\bregistry\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\"V\n" +
	"\x14FetchCVMFSParameters\x12\x16\n" +
	"\x06mirror\x18\x01 \x01(\tR\x06mirror\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"G\n" +
	"\x16ReadOciImageParameters\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.proto.BuildDefinitionRefR\x04base\"1\n" +
	"\x0eFileParameters\x12\x1f\n" +
	"\x04file\x18\x01 \x01(\v2\v.proto.FileR\x04file\",\n" +
	"\x16ConstantHashParameters\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"Z\n" +
	"\x15ExtractFileParameters\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.proto.BuildDefinitionRefR\x04base\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x96\x01\n" +
	"\x0ePlanParameters\x12\x18\n" +
	"\abuilder\x18\x01 \x01(\tR\abuilder\x12\"\n" +
	"\farchitecture\x18\x02 \x01(\tR\farchitecture\x12+\n" +
	"\x06search\x18\x03 \x03(\v2\x13.proto.PackageQueryR\x06search\x12\x19\n" +
	"\btag_list\x18\x04 \x03(\tR\atagList\"\x85\x01\n" +
	"\x15ReadArchiveParameters\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.proto.BuildDefinitionRefR\x04base\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12)\n" +
	"\x10strip_components\x18\x03 \x01(\x05R\x0fstripComponents\"\x94\x01\n" +
	"\x0eStarParameters\x12'\n" +
	"\x0fscript_filename\x18\x01 \x01(\tR\x0escriptFilename\x12!\n" +
	"\fbuilder_name\x18\x02 \x01(\tR\vbuilderName\x126\n" +
	"\targuments\x18\x03 \x03(\v2\x18.proto.SerializableValueR\targumentsb\x06proto3"

var (
	file_definition_proto_rawDescOnce sync.Once
	file_definition_proto_rawDescData []byte
)

func file_definition_proto_rawDescGZIP() []byte {
	file_definition_proto_rawDescOnce.Do(func() {
		file_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_definition_proto_rawDesc), len(file_definition_proto_rawDesc)))
	})
	return file_definition_proto_rawDescData
}

var file_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_definition_proto_goTypes = []any{
	(*BuildDefinition)(nil),           // 0: proto.BuildDefinition
	(*BuildFsParameters)(nil),         // 1: proto.BuildFsParameters
	(*BuildVmParameters)(nil),         // 2: proto.BuildVmParameters
	(*BuildEmulatorParameters)(nil),   // 3: proto.BuildEmulatorParameters
	(*DecompressFileParameters)(nil),  // 4: proto.DecompressFileParameters
	(*FetchHttpParameters)(nil),       // 5: proto.FetchHttpParameters
	(*RegistryRequestParameters)(nil), // 6: proto.RegistryRequestParameters
	(*FetchOciImageParameters)(nil),   // 7: proto.FetchOciImageParameters
	(*FetchCVMFSParameters)(nil),      // 8: proto.FetchCVMFSParameters
	(*ReadOciImageParameters)(nil),    // 9: proto.ReadOciImageParameters
	(*FileParameters)(nil),            // 10: proto.FileParameters
	(*ConstantHashParameters)(nil),    // 11: proto.ConstantHashParameters
	(*ExtractFileParameters)(nil),     // 12: proto.ExtractFileParameters
	(*PlanParameters)(nil),            // 13: proto.PlanParameters
	(*ReadArchiveParameters)(nil),     // 14: proto.ReadArchiveParameters
	(*StarParameters)(nil),            // 15: proto.StarParameters
	nil,                               // 16: proto.FetchHttpParameters.HeadersEntry
	(*Directive)(nil),                 // 17: proto.Directive
	(*BuildDefinitionRef)(nil),        // 18: proto.BuildDefinitionRef
	(*File)(nil),                      // 19: proto.File
	(*PackageQuery)(nil),              // 20: proto.PackageQuery
	(*SerializableValue)(nil),         // 21: proto.SerializableValue
}
var file_definition_proto_depIdxs = []int32{
	1,  // 0: proto.BuildDefinition.build_fs:type_name -> proto.BuildFsParameters
	2,  // 1: proto.BuildDefinition.build_vm:type_name -> proto.BuildVmParameters
	3,  // 2: proto.BuildDefinition.build_emulator:type_name -> proto.BuildEmulatorParameters
	4,  // 3: proto.BuildDefinition.decompress_file:type_name -> proto.DecompressFileParameters
	5,  // 4: proto.BuildDefinition.fetch_http:type_name -> proto.FetchHttpParameters
	6,  // 5: proto.BuildDefinition.registry_request:type_name -> proto.RegistryRequestParameters
	7,  // 6: proto.BuildDefinition.fetch_oci_image:type_name -> proto.FetchOciImageParameters
	8,  // 7: proto.BuildDefinition.fetch_cvmfs:type_name -> proto.FetchCVMFSParameters
	9,  // 8: proto.BuildDefinition.read_oci_image:type_name -> proto.ReadOciImageParameters
	10, // 9: proto.BuildDefinition.file:type_name -> proto.FileParameters
	11, // 10: proto.BuildDefinition.constant_hash:type_name -> proto.ConstantHashParameters
	12, // 11: proto.BuildDefinition.extract_file:type_name -> proto.ExtractFileParameters
	13, // 12: proto.BuildDefinition.plan:type_name -> proto.PlanParameters
	14, // 13: proto.BuildDefinition.read_archive:type_name -> proto.ReadArchiveParameters
	15, // 14: proto.BuildDefinition.star:type_name -> proto.StarParameters
	17, // 15: proto.BuildFsParameters.directives:type_name -> proto.Directive
	17, // 16: proto.BuildVmParameters.directives:type_name -> proto.Directive
	18, // 17: proto.BuildVmParameters.kernel:type_name -> proto.BuildDefinitionRef
	18, // 18: proto.BuildVmParameters.init_ram_fs:type_name -> proto.BuildDefinitionRef
	17, // 19: proto.BuildEmulatorParameters.directives:type_name -> proto.Directive
	18, // 20: proto.DecompressFileParameters.base:type_name -> proto.BuildDefinitionRef
	16, // 21: proto.FetchHttpParameters.headers:type_name -> proto.FetchHttpParameters.HeadersEntry
	18, // 22: proto.ReadOciImageParameters.base:type_name -> proto.BuildDefinitionRef
	19, // 23: proto.FileParameters.file:type_name -> proto.File
	18, // 24: proto.ExtractFileParameters.base:type_name -> proto.BuildDefinitionRef
	20, // 25: proto.PlanParameters.search:type_name -> proto.PackageQuery
	18, // 26: proto.ReadArchiveParameters.base:type_name -> proto.BuildDefinitionRef
	21, // 27: proto.StarParameters.arguments:type_name -> proto.SerializableValue
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_definition_proto_init() }
func file_definition_proto_init() {
	if File_definition_proto != nil {
		return
	}
	file_common_proto_init()
	file_directive_proto_init()
	file_definition_proto_msgTypes[0].OneofWrappers = []any{
		(*BuildDefinition_BuildFs)(nil),
		(*BuildDefinition_BuildVm)(nil),
		(*BuildDefinition_BuildEmulator)(nil),
		(*BuildDefinition_DecompressFile)(nil),
		(*BuildDefinition_FetchHttp)(nil),
		(*BuildDefinition_RegistryRequest)(nil),
		(*BuildDefinition_FetchOciImage)(nil),
		(*BuildDefinition_FetchCvmfs)(nil),
		(*BuildDefinition_ReadOciImage)(nil),
		(*BuildDefinition_File)(nil),
		(*BuildDefinition_ConstantHash)(nil),
		(*BuildDefinition_ExtractFile)(nil),
		(*BuildDefinition_Plan)(nil),
		(*BuildDefinition_ReadArchive)(nil),
		(*BuildDefinition_Star)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_definition_proto_rawDesc), len(file_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_definition_proto_goTypes,
		DependencyIndexes: file_definition_proto_depIdxs,
		MessageInfos:      file_definition_proto_msgTypes,
	}.Build()
	File_definition_proto = out.File
	file_definition_proto_goTypes = nil
	file_definition_proto_depIdxs = nil
}
