// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: directive.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Run a command inside the build.
type DirectiveRunCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` // The command to run
	Raw           bool                   `protobuf:"varint,2,opt,name=raw,proto3" json:"raw,omitempty"`        // If true, run without shell wrapping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveRunCommand) Reset() {
	*x = DirectiveRunCommand{}
	mi := &file_directive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveRunCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveRunCommand) ProtoMessage() {}

func (x *DirectiveRunCommand) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveRunCommand.ProtoReflect.Descriptor instead.
func (*DirectiveRunCommand) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{0}
}

func (x *DirectiveRunCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *DirectiveRunCommand) GetRaw() bool {
	if x != nil {
		return x.Raw
	}
	return false
}

// Start a service inside the build.
type DirectiveStartServiceCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` // The service command to run
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveStartServiceCommand) Reset() {
	*x = DirectiveStartServiceCommand{}
	mi := &file_directive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveStartServiceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveStartServiceCommand) ProtoMessage() {}

func (x *DirectiveStartServiceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveStartServiceCommand.ProtoReflect.Descriptor instead.
func (*DirectiveStartServiceCommand) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{1}
}

func (x *DirectiveStartServiceCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// Run a Starlark script.
type DirectiveRunStarlarkScript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"` // The script contents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveRunStarlarkScript) Reset() {
	*x = DirectiveRunStarlarkScript{}
	mi := &file_directive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveRunStarlarkScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveRunStarlarkScript) ProtoMessage() {}

func (x *DirectiveRunStarlarkScript) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveRunStarlarkScript.ProtoReflect.Descriptor instead.
func (*DirectiveRunStarlarkScript) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{2}
}

func (x *DirectiveRunStarlarkScript) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

// Add a file to the build.
type DirectiveAddFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`      // Guest filename
	Definition    *BuildDefinitionRef    `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`  // Optional reference to a build definition
	Contents      []byte                 `protobuf:"bytes,3,opt,name=contents,proto3" json:"contents,omitempty"`      // Raw file contents
	Executable    bool                   `protobuf:"varint,4,opt,name=executable,proto3" json:"executable,omitempty"` // Whether the file is executable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveAddFile) Reset() {
	*x = DirectiveAddFile{}
	mi := &file_directive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveAddFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveAddFile) ProtoMessage() {}

func (x *DirectiveAddFile) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveAddFile.ProtoReflect.Descriptor instead.
func (*DirectiveAddFile) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{3}
}

func (x *DirectiveAddFile) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DirectiveAddFile) GetDefinition() *BuildDefinitionRef {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *DirectiveAddFile) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *DirectiveAddFile) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

// Add a file from the host filesystem.
type DirectiveLocalFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                             // Guest filename
	HostFilename  string                 `protobuf:"bytes,2,opt,name=host_filename,json=hostFilename,proto3" json:"host_filename,omitempty"` // Host filename
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveLocalFile) Reset() {
	*x = DirectiveLocalFile{}
	mi := &file_directive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveLocalFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveLocalFile) ProtoMessage() {}

func (x *DirectiveLocalFile) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveLocalFile.ProtoReflect.Descriptor instead.
func (*DirectiveLocalFile) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{4}
}

func (x *DirectiveLocalFile) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DirectiveLocalFile) GetHostFilename() string {
	if x != nil {
		return x.HostFilename
	}
	return ""
}

// Add a directory from the host filesystem.
type DirectiveLocalDirectory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostDirectory  string                 `protobuf:"bytes,1,opt,name=host_directory,json=hostDirectory,proto3" json:"host_directory,omitempty"`    // Host directory path
	GuestDirectory string                 `protobuf:"bytes,2,opt,name=guest_directory,json=guestDirectory,proto3" json:"guest_directory,omitempty"` // Guest directory path
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DirectiveLocalDirectory) Reset() {
	*x = DirectiveLocalDirectory{}
	mi := &file_directive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveLocalDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveLocalDirectory) ProtoMessage() {}

func (x *DirectiveLocalDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveLocalDirectory.ProtoReflect.Descriptor instead.
func (*DirectiveLocalDirectory) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{5}
}

func (x *DirectiveLocalDirectory) GetHostDirectory() string {
	if x != nil {
		return x.HostDirectory
	}
	return ""
}

func (x *DirectiveLocalDirectory) GetGuestDirectory() string {
	if x != nil {
		return x.GuestDirectory
	}
	return ""
}

// Add an archive to the build.
type DirectiveArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *BuildDefinitionRef    `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"` // Reference to archive build definition
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`         // Target path inside guest
	Archive2      bool                   `protobuf:"varint,3,opt,name=archive2,proto3" json:"archive2,omitempty"`    // Whether to use archive2 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveArchive) Reset() {
	*x = DirectiveArchive{}
	mi := &file_directive_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveArchive) ProtoMessage() {}

func (x *DirectiveArchive) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveArchive.ProtoReflect.Descriptor instead.
func (*DirectiveArchive) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{6}
}

func (x *DirectiveArchive) GetDefinition() *BuildDefinitionRef {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *DirectiveArchive) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DirectiveArchive) GetArchive2() bool {
	if x != nil {
		return x.Archive2
	}
	return false
}

// Export a port from the build.
type DirectiveExportPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                        // Port name
	ListenAddress string                 `protobuf:"bytes,2,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"` // Default is localhost
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                                       // Port number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveExportPort) Reset() {
	*x = DirectiveExportPort{}
	mi := &file_directive_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveExportPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveExportPort) ProtoMessage() {}

func (x *DirectiveExportPort) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveExportPort.ProtoReflect.Descriptor instead.
func (*DirectiveExportPort) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{7}
}

func (x *DirectiveExportPort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirectiveExportPort) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

func (x *DirectiveExportPort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Set environment variables.
type DirectiveEnvironment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variables     []string               `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty"` // List of environment variables
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveEnvironment) Reset() {
	*x = DirectiveEnvironment{}
	mi := &file_directive_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveEnvironment) ProtoMessage() {}

func (x *DirectiveEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveEnvironment.ProtoReflect.Descriptor instead.
func (*DirectiveEnvironment) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{8}
}

func (x *DirectiveEnvironment) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

// Use a builtin artifact.
type DirectiveBuiltin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                        // Builtin name
	Architecture  string                 `protobuf:"bytes,2,opt,name=architecture,proto3" json:"architecture,omitempty"`                        // CPU architecture
	GuestFilename string                 `protobuf:"bytes,3,opt,name=guest_filename,json=guestFilename,proto3" json:"guest_filename,omitempty"` // Guest filename
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveBuiltin) Reset() {
	*x = DirectiveBuiltin{}
	mi := &file_directive_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveBuiltin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveBuiltin) ProtoMessage() {}

func (x *DirectiveBuiltin) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveBuiltin.ProtoReflect.Descriptor instead.
func (*DirectiveBuiltin) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{9}
}

func (x *DirectiveBuiltin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirectiveBuiltin) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *DirectiveBuiltin) GetGuestFilename() string {
	if x != nil {
		return x.GuestFilename
	}
	return ""
}

// A list of directives.
type DirectiveList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Directive           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // Nested directives
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveList) Reset() {
	*x = DirectiveList{}
	mi := &file_directive_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveList) ProtoMessage() {}

func (x *DirectiveList) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveList.ProtoReflect.Descriptor instead.
func (*DirectiveList) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{10}
}

func (x *DirectiveList) GetItems() []*Directive {
	if x != nil {
		return x.Items
	}
	return nil
}

// Add a package to the build.
type DirectiveAddPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageQuery  string                 `protobuf:"bytes,1,opt,name=package_query,json=packageQuery,proto3" json:"package_query,omitempty"` // Package query string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveAddPackage) Reset() {
	*x = DirectiveAddPackage{}
	mi := &file_directive_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveAddPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveAddPackage) ProtoMessage() {}

func (x *DirectiveAddPackage) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveAddPackage.ProtoReflect.Descriptor instead.
func (*DirectiveAddPackage) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{11}
}

func (x *DirectiveAddPackage) GetPackageQuery() string {
	if x != nil {
		return x.PackageQuery
	}
	return ""
}

// Add an interaction directive.
type DirectiveInteraction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interaction   string                 `protobuf:"bytes,1,opt,name=interaction,proto3" json:"interaction,omitempty"` // Interaction type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveInteraction) Reset() {
	*x = DirectiveInteraction{}
	mi := &file_directive_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveInteraction) ProtoMessage() {}

func (x *DirectiveInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveInteraction.ProtoReflect.Descriptor instead.
func (*DirectiveInteraction) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{12}
}

func (x *DirectiveInteraction) GetInteraction() string {
	if x != nil {
		return x.Interaction
	}
	return ""
}

// Set a default interactive command.
type DirectiveDefaultInteractive struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InteractiveCommand []string               `protobuf:"bytes,1,rep,name=interactive_command,json=interactiveCommand,proto3" json:"interactive_command,omitempty"` // Command arguments
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DirectiveDefaultInteractive) Reset() {
	*x = DirectiveDefaultInteractive{}
	mi := &file_directive_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveDefaultInteractive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveDefaultInteractive) ProtoMessage() {}

func (x *DirectiveDefaultInteractive) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveDefaultInteractive.ProtoReflect.Descriptor instead.
func (*DirectiveDefaultInteractive) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{13}
}

func (x *DirectiveDefaultInteractive) GetInteractiveCommand() []string {
	if x != nil {
		return x.InteractiveCommand
	}
	return nil
}

// Mount a host directory into the guest.
type DirectiveMountHostDirectory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostDirectory  string                 `protobuf:"bytes,1,opt,name=host_directory,json=hostDirectory,proto3" json:"host_directory,omitempty"`    // Host directory path
	GuestDirectory string                 `protobuf:"bytes,2,opt,name=guest_directory,json=guestDirectory,proto3" json:"guest_directory,omitempty"` // Guest directory path
	Port           int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                                          // Only used for 9p
	Writable       bool                   `protobuf:"varint,4,opt,name=writable,proto3" json:"writable,omitempty"`                                  // Whether the mount is writable
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DirectiveMountHostDirectory) Reset() {
	*x = DirectiveMountHostDirectory{}
	mi := &file_directive_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveMountHostDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveMountHostDirectory) ProtoMessage() {}

func (x *DirectiveMountHostDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveMountHostDirectory.ProtoReflect.Descriptor instead.
func (*DirectiveMountHostDirectory) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{14}
}

func (x *DirectiveMountHostDirectory) GetHostDirectory() string {
	if x != nil {
		return x.HostDirectory
	}
	return ""
}

func (x *DirectiveMountHostDirectory) GetGuestDirectory() string {
	if x != nil {
		return x.GuestDirectory
	}
	return ""
}

func (x *DirectiveMountHostDirectory) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DirectiveMountHostDirectory) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

// Add a kernel/initramfs pair.
type DirectiveKernel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kernel        *BuildDefinitionRef    `protobuf:"bytes,1,opt,name=kernel,proto3" json:"kernel,omitempty"`       // Kernel build definition
	Initramfs     *BuildDefinitionRef    `protobuf:"bytes,2,opt,name=initramfs,proto3" json:"initramfs,omitempty"` // Initramfs build definition
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveKernel) Reset() {
	*x = DirectiveKernel{}
	mi := &file_directive_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveKernel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveKernel) ProtoMessage() {}

func (x *DirectiveKernel) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveKernel.ProtoReflect.Descriptor instead.
func (*DirectiveKernel) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{15}
}

func (x *DirectiveKernel) GetKernel() *BuildDefinitionRef {
	if x != nil {
		return x.Kernel
	}
	return nil
}

func (x *DirectiveKernel) GetInitramfs() *BuildDefinitionRef {
	if x != nil {
		return x.Initramfs
	}
	return nil
}

// Add an init script.
type DirectiveAddInitScript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuestFilename string                 `protobuf:"bytes,1,opt,name=guest_filename,json=guestFilename,proto3" json:"guest_filename,omitempty"` // Guest filename for init script
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveAddInitScript) Reset() {
	*x = DirectiveAddInitScript{}
	mi := &file_directive_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveAddInitScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveAddInitScript) ProtoMessage() {}

func (x *DirectiveAddInitScript) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveAddInitScript.ProtoReflect.Descriptor instead.
func (*DirectiveAddInitScript) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{16}
}

func (x *DirectiveAddInitScript) GetGuestFilename() string {
	if x != nil {
		return x.GuestFilename
	}
	return ""
}

// Add a volume to the build.
type DirectiveAddVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeName    string                 `protobuf:"bytes,1,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`             // Volume name
	GuestPath     string                 `protobuf:"bytes,2,opt,name=guest_path,json=guestPath,proto3" json:"guest_path,omitempty"`                // Guest path
	MinimumSizeMb uint64                 `protobuf:"varint,3,opt,name=minimum_size_mb,json=minimumSizeMb,proto3" json:"minimum_size_mb,omitempty"` // Minimum size in MB
	Persist       bool                   `protobuf:"varint,4,opt,name=persist,proto3" json:"persist,omitempty"`                                    // Whether the volume persists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveAddVolume) Reset() {
	*x = DirectiveAddVolume{}
	mi := &file_directive_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveAddVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveAddVolume) ProtoMessage() {}

func (x *DirectiveAddVolume) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveAddVolume.ProtoReflect.Descriptor instead.
func (*DirectiveAddVolume) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{17}
}

func (x *DirectiveAddVolume) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *DirectiveAddVolume) GetGuestPath() string {
	if x != nil {
		return x.GuestPath
	}
	return ""
}

func (x *DirectiveAddVolume) GetMinimumSizeMb() uint64 {
	if x != nil {
		return x.MinimumSizeMb
	}
	return 0
}

func (x *DirectiveAddVolume) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

// ----------------------
// Directive Union
// ----------------------
// A Directive is one of the above variants.
type Directive struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Directive:
	//
	//	*Directive_RunCommand
	//	*Directive_StartServiceCommand
	//	*Directive_RunStarlarkScript
	//	*Directive_AddFile
	//	*Directive_LocalFile
	//	*Directive_LocalDirectory
	//	*Directive_Archive
	//	*Directive_ExportPort
	//	*Directive_Environment
	//	*Directive_Builtin
	//	*Directive_List
	//	*Directive_AddPackage
	//	*Directive_Interaction
	//	*Directive_DefaultInteractive
	//	*Directive_MountHostDirectory
	//	*Directive_Kernel
	//	*Directive_AddInitScript
	//	*Directive_AddVolume
	Directive     isDirective_Directive `protobuf_oneof:"directive"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directive) Reset() {
	*x = Directive{}
	mi := &file_directive_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directive) ProtoMessage() {}

func (x *Directive) ProtoReflect() protoreflect.Message {
	mi := &file_directive_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directive.ProtoReflect.Descriptor instead.
func (*Directive) Descriptor() ([]byte, []int) {
	return file_directive_proto_rawDescGZIP(), []int{18}
}

func (x *Directive) GetDirective() isDirective_Directive {
	if x != nil {
		return x.Directive
	}
	return nil
}

func (x *Directive) GetRunCommand() *DirectiveRunCommand {
	if x != nil {
		if x, ok := x.Directive.(*Directive_RunCommand); ok {
			return x.RunCommand
		}
	}
	return nil
}

func (x *Directive) GetStartServiceCommand() *DirectiveStartServiceCommand {
	if x != nil {
		if x, ok := x.Directive.(*Directive_StartServiceCommand); ok {
			return x.StartServiceCommand
		}
	}
	return nil
}

func (x *Directive) GetRunStarlarkScript() *DirectiveRunStarlarkScript {
	if x != nil {
		if x, ok := x.Directive.(*Directive_RunStarlarkScript); ok {
			return x.RunStarlarkScript
		}
	}
	return nil
}

func (x *Directive) GetAddFile() *DirectiveAddFile {
	if x != nil {
		if x, ok := x.Directive.(*Directive_AddFile); ok {
			return x.AddFile
		}
	}
	return nil
}

func (x *Directive) GetLocalFile() *DirectiveLocalFile {
	if x != nil {
		if x, ok := x.Directive.(*Directive_LocalFile); ok {
			return x.LocalFile
		}
	}
	return nil
}

func (x *Directive) GetLocalDirectory() *DirectiveLocalDirectory {
	if x != nil {
		if x, ok := x.Directive.(*Directive_LocalDirectory); ok {
			return x.LocalDirectory
		}
	}
	return nil
}

func (x *Directive) GetArchive() *DirectiveArchive {
	if x != nil {
		if x, ok := x.Directive.(*Directive_Archive); ok {
			return x.Archive
		}
	}
	return nil
}

func (x *Directive) GetExportPort() *DirectiveExportPort {
	if x != nil {
		if x, ok := x.Directive.(*Directive_ExportPort); ok {
			return x.ExportPort
		}
	}
	return nil
}

func (x *Directive) GetEnvironment() *DirectiveEnvironment {
	if x != nil {
		if x, ok := x.Directive.(*Directive_Environment); ok {
			return x.Environment
		}
	}
	return nil
}

func (x *Directive) GetBuiltin() *DirectiveBuiltin {
	if x != nil {
		if x, ok := x.Directive.(*Directive_Builtin); ok {
			return x.Builtin
		}
	}
	return nil
}

func (x *Directive) GetList() *DirectiveList {
	if x != nil {
		if x, ok := x.Directive.(*Directive_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Directive) GetAddPackage() *DirectiveAddPackage {
	if x != nil {
		if x, ok := x.Directive.(*Directive_AddPackage); ok {
			return x.AddPackage
		}
	}
	return nil
}

func (x *Directive) GetInteraction() *DirectiveInteraction {
	if x != nil {
		if x, ok := x.Directive.(*Directive_Interaction); ok {
			return x.Interaction
		}
	}
	return nil
}

func (x *Directive) GetDefaultInteractive() *DirectiveDefaultInteractive {
	if x != nil {
		if x, ok := x.Directive.(*Directive_DefaultInteractive); ok {
			return x.DefaultInteractive
		}
	}
	return nil
}

func (x *Directive) GetMountHostDirectory() *DirectiveMountHostDirectory {
	if x != nil {
		if x, ok := x.Directive.(*Directive_MountHostDirectory); ok {
			return x.MountHostDirectory
		}
	}
	return nil
}

func (x *Directive) GetKernel() *DirectiveKernel {
	if x != nil {
		if x, ok := x.Directive.(*Directive_Kernel); ok {
			return x.Kernel
		}
	}
	return nil
}

func (x *Directive) GetAddInitScript() *DirectiveAddInitScript {
	if x != nil {
		if x, ok := x.Directive.(*Directive_AddInitScript); ok {
			return x.AddInitScript
		}
	}
	return nil
}

func (x *Directive) GetAddVolume() *DirectiveAddVolume {
	if x != nil {
		if x, ok := x.Directive.(*Directive_AddVolume); ok {
			return x.AddVolume
		}
	}
	return nil
}

type isDirective_Directive interface {
	isDirective_Directive()
}

type Directive_RunCommand struct {
	RunCommand *DirectiveRunCommand `protobuf:"bytes,1,opt,name=run_command,json=runCommand,proto3,oneof"`
}

type Directive_StartServiceCommand struct {
	StartServiceCommand *DirectiveStartServiceCommand `protobuf:"bytes,2,opt,name=start_service_command,json=startServiceCommand,proto3,oneof"`
}

type Directive_RunStarlarkScript struct {
	RunStarlarkScript *DirectiveRunStarlarkScript `protobuf:"bytes,3,opt,name=run_starlark_script,json=runStarlarkScript,proto3,oneof"`
}

type Directive_AddFile struct {
	AddFile *DirectiveAddFile `protobuf:"bytes,4,opt,name=add_file,json=addFile,proto3,oneof"`
}

type Directive_LocalFile struct {
	LocalFile *DirectiveLocalFile `protobuf:"bytes,5,opt,name=local_file,json=localFile,proto3,oneof"`
}

type Directive_LocalDirectory struct {
	LocalDirectory *DirectiveLocalDirectory `protobuf:"bytes,6,opt,name=local_directory,json=localDirectory,proto3,oneof"`
}

type Directive_Archive struct {
	Archive *DirectiveArchive `protobuf:"bytes,7,opt,name=archive,proto3,oneof"`
}

type Directive_ExportPort struct {
	ExportPort *DirectiveExportPort `protobuf:"bytes,8,opt,name=export_port,json=exportPort,proto3,oneof"`
}

type Directive_Environment struct {
	Environment *DirectiveEnvironment `protobuf:"bytes,9,opt,name=environment,proto3,oneof"`
}

type Directive_Builtin struct {
	Builtin *DirectiveBuiltin `protobuf:"bytes,10,opt,name=builtin,proto3,oneof"`
}

type Directive_List struct {
	List *DirectiveList `protobuf:"bytes,11,opt,name=list,proto3,oneof"`
}

type Directive_AddPackage struct {
	AddPackage *DirectiveAddPackage `protobuf:"bytes,12,opt,name=add_package,json=addPackage,proto3,oneof"`
}

type Directive_Interaction struct {
	Interaction *DirectiveInteraction `protobuf:"bytes,13,opt,name=interaction,proto3,oneof"`
}

type Directive_DefaultInteractive struct {
	DefaultInteractive *DirectiveDefaultInteractive `protobuf:"bytes,14,opt,name=default_interactive,json=defaultInteractive,proto3,oneof"`
}

type Directive_MountHostDirectory struct {
	MountHostDirectory *DirectiveMountHostDirectory `protobuf:"bytes,15,opt,name=mount_host_directory,json=mountHostDirectory,proto3,oneof"`
}

type Directive_Kernel struct {
	Kernel *DirectiveKernel `protobuf:"bytes,16,opt,name=kernel,proto3,oneof"`
}

type Directive_AddInitScript struct {
	AddInitScript *DirectiveAddInitScript `protobuf:"bytes,17,opt,name=add_init_script,json=addInitScript,proto3,oneof"`
}

type Directive_AddVolume struct {
	AddVolume *DirectiveAddVolume `protobuf:"bytes,18,opt,name=add_volume,json=addVolume,proto3,oneof"`
}

func (*Directive_RunCommand) isDirective_Directive() {}

func (*Directive_StartServiceCommand) isDirective_Directive() {}

func (*Directive_RunStarlarkScript) isDirective_Directive() {}

func (*Directive_AddFile) isDirective_Directive() {}

func (*Directive_LocalFile) isDirective_Directive() {}

func (*Directive_LocalDirectory) isDirective_Directive() {}

func (*Directive_Archive) isDirective_Directive() {}

func (*Directive_ExportPort) isDirective_Directive() {}

func (*Directive_Environment) isDirective_Directive() {}

func (*Directive_Builtin) isDirective_Directive() {}

func (*Directive_List) isDirective_Directive() {}

func (*Directive_AddPackage) isDirective_Directive() {}

func (*Directive_Interaction) isDirective_Directive() {}

func (*Directive_DefaultInteractive) isDirective_Directive() {}

func (*Directive_MountHostDirectory) isDirective_Directive() {}

func (*Directive_Kernel) isDirective_Directive() {}

func (*Directive_AddInitScript) isDirective_Directive() {}

func (*Directive_AddVolume) isDirective_Directive() {}

var File_directive_proto protoreflect.FileDescriptor

const file_directive_proto_rawDesc = "" +
	"\n" +
	"\x0fdirective.proto\x12\x05proto\x1a\fcommon.proto\"A\n" +
	"\x13DirectiveRunCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\bR\x03raw\"8\n" +
	"\x1cDirectiveStartServiceCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"4\n" +
	"\x1aDirectiveRunStarlarkScript\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\"\xa5\x01\n" +
	"\x10DirectiveAddFile\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x129\n" +
	"\n" +
	"definition\x18\x02 \x01(\v2\x19.proto.BuildDefinitionRefR\n" +
	"definition\x12\x1a\n" +
	"\bcontents\x18\x03 \x01(\fR\bcontents\x12\x1e\n" +
	"\n" +
	"executable\x18\x04 \x01(\bR\n" +
	"executable\"U\n" +
	"\x12DirectiveLocalFile\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12#\n" +
	"\rhost_filename\x18\x02 \x01(\tR\fhostFilename\"i\n" +
	"\x17DirectiveLocalDirectory\x12%\n" +
	"\x0ehost_directory\x18\x01 \x01(\tR\rhostDirectory\x12'\n" +
	"\x0fguest_directory\x18\x02 \x01(\tR\x0eguestDirectory\"\x81\x01\n" +
	"\x10DirectiveArchive\x129\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2\x19.proto.BuildDefinitionRefR\n" +
	"definition\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1a\n" +
	"\barchive2\x18\x03 \x01(\bR\barchive2\"d\n" +
	"\x13DirectiveExportPort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0elisten_address\x18\x02 \x01(\tR\rlistenAddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"4\n" +
	"\x14DirectiveEnvironment\x12\x1c\n" +
	"\tvariables\x18\x01 \x03(\tR\tvariables\"q\n" +
	"\x10DirectiveBuiltin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\farchitecture\x18\x02 \x01(\tR\farchitecture\x12%\n" +
	"\x0eguest_filename\x18\x03 \x01(\tR\rguestFilename\"7\n" +
	"\rDirectiveList\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.proto.DirectiveR\x05items\":\n" +
	"\x13DirectiveAddPackage\x12#\n" +
	"\rpackage_query\x18\x01 \x01(\tR\fpackageQuery\"8\n" +
	"\x14DirectiveInteraction\x12 \n" +
	"\vinteraction\x18\x01 \x01(\tR\vinteraction\"N\n" +
	"\x1bDirectiveDefaultInteractive\x12/\n" +
	"\x13interactive_command\x18\x01 \x03(\tR\x12interactiveCommand\"\x9d\x01\n" +
	"\x1bDirectiveMountHostDirectory\x12%\n" +
	"\x0ehost_directory\x18\x01 \x01(\tR\rhostDirectory\x12'\n" +
	"\x0fguest_directory\x18\x02 \x01(\tR\x0eguestDirectory\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\bwritable\x18\x04 \x01(\bR\bwritable\"}\n" +
	"\x0fDirectiveKernel\x121\n" +
	"\x06kernel\x18\x01 \x01(\v2\x19.proto.BuildDefinitionRefR\x06kernel\x127\n" +
	"\tinitramfs\x18\x02 \x01(\v2\x19.proto.BuildDefinitionRefR\tinitramfs\"?\n" +
	"\x16DirectiveAddInitScript\x12%\n" +
	"\x0eguest_filename\x18\x01 \x01(\tR\rguestFilename\"\x96\x01\n" +
	"\x12DirectiveAddVolume\x12\x1f\n" +
	"\vvolume_name\x18\x01 \x01(\tR\n" +
	"volumeName\x12\x1d\n" +
	"\n" +
	"guest_path\x18\x02 \x01(\tR\tguestPath\x12&\n" +
	"\x0fminimum_size_mb\x18\x03 \x01(\x04R\rminimumSizeMb\x12\x18\n" +
	"\apersist\x18\x04 \x01(\bR\apersist\"\xc0\t\n" +
	"\tDirective\x12=\n" +
	"\vrun_command\x18\x01 \x01(\v2\x1a.proto.DirectiveRunCommandH\x00R\n" +
	"runCommand\x12Y\n" +
	"\x15start_service_command\x18\x02 \x01(\v2#.proto.DirectiveStartServiceCommandH\x00R\x13startServiceCommand\x12S\n" +
	"\x13run_starlark_script\x18\x03 \x01(\v2!.proto.DirectiveRunStarlarkScriptH\x00R\x11runStarlarkScript\x124\n" +
	"\badd_file\x18\x04 \x01(\v2\x17.proto.DirectiveAddFileH\x00R\aaddFile\x12:\n" +
	"\n" +
	"local_file\x18\x05 \x01(\v2\x19.proto.DirectiveLocalFileH\x00R\tlocalFile\x12I\n" +
	"\x0flocal_directory\x18\x06 \x01(\v2\x1e.proto.DirectiveLocalDirectoryH\x00R\x0elocalDirectory\x123\n" +
	"\aarchive\x18\a \x01(\v2\x17.proto.DirectiveArchiveH\x00R\aarchive\x12=\n" +
	"\vexport_port\x18\b \x01(\v2\x1a.proto.DirectiveExportPortH\x00R\n" +
	"exportPort\x12?\n" +
	"\venvironment\x18\t \x01(\v2\x1b.proto.DirectiveEnvironmentH\x00R\venvironment\x123\n" +
	"\abuiltin\x18\n" +
	" \x01(\v2\x17.proto.DirectiveBuiltinH\x00R\abuiltin\x12*\n" +
	"\x04list\x18\v \x01(\v2\x14.proto.DirectiveListH\x00R\x04list\x12=\n" +
	"\vadd_package\x18\f \x01(\v2\x1a.proto.DirectiveAddPackageH\x00R\n" +
	"addPackage\x12?\n" +
	"\vinteraction\x18\r \x01(\v2\x1b.proto.DirectiveInteractionH\x00R\vinteraction\x12U\n" +
	"\x13default_interactive\x18\x0e \x01(\v2\".proto.DirectiveDefaultInteractiveH\x00R\x12defaultInteractive\x12V\n" +
	"\x14mount_host_directory\x18\x0f \x01(\v2\".proto.DirectiveMountHostDirectoryH\x00R\x12mountHostDirectory\x120\n" +
	"\x06kernel\x18\x10 \x01(\v2\x16.proto.DirectiveKernelH\x00R\x06kernel\x12G\n" +
	"\x0fadd_init_script\x18\x11 \x01(\v2\x1d.proto.DirectiveAddInitScriptH\x00R\raddInitScript\x12:\n" +
	"\n" +
	"add_volume\x18\x12 \x01(\v2\x19.proto.DirectiveAddVolumeH\x00R\taddVolumeB\v\n" +
	"\tdirectiveb\x06proto3"

var (
	file_directive_proto_rawDescOnce sync.Once
	file_directive_proto_rawDescData []byte
)

func file_directive_proto_rawDescGZIP() []byte {
	file_directive_proto_rawDescOnce.Do(func() {
		file_directive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directive_proto_rawDesc), len(file_directive_proto_rawDesc)))
	})
	return file_directive_proto_rawDescData
}

var file_directive_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_directive_proto_goTypes = []any{
	(*DirectiveRunCommand)(nil),          // 0: proto.DirectiveRunCommand
	(*DirectiveStartServiceCommand)(nil), // 1: proto.DirectiveStartServiceCommand
	(*DirectiveRunStarlarkScript)(nil),   // 2: proto.DirectiveRunStarlarkScript
	(*DirectiveAddFile)(nil),             // 3: proto.DirectiveAddFile
	(*DirectiveLocalFile)(nil),           // 4: proto.DirectiveLocalFile
	(*DirectiveLocalDirectory)(nil),      // 5: proto.DirectiveLocalDirectory
	(*DirectiveArchive)(nil),             // 6: proto.DirectiveArchive
	(*DirectiveExportPort)(nil),          // 7: proto.DirectiveExportPort
	(*DirectiveEnvironment)(nil),         // 8: proto.DirectiveEnvironment
	(*DirectiveBuiltin)(nil),             // 9: proto.DirectiveBuiltin
	(*DirectiveList)(nil),                // 10: proto.DirectiveList
	(*DirectiveAddPackage)(nil),          // 11: proto.DirectiveAddPackage
	(*DirectiveInteraction)(nil),         // 12: proto.DirectiveInteraction
	(*DirectiveDefaultInteractive)(nil),  // 13: proto.DirectiveDefaultInteractive
	(*DirectiveMountHostDirectory)(nil),  // 14: proto.DirectiveMountHostDirectory
	(*DirectiveKernel)(nil),              // 15: proto.DirectiveKernel
	(*DirectiveAddInitScript)(nil),       // 16: proto.DirectiveAddInitScript
	(*DirectiveAddVolume)(nil),           // 17: proto.DirectiveAddVolume
	(*Directive)(nil),                    // 18: proto.Directive
	(*BuildDefinitionRef)(nil),           // 19: proto.BuildDefinitionRef
}
var file_directive_proto_depIdxs = []int32{
	19, // 0: proto.DirectiveAddFile.definition:type_name -> proto.BuildDefinitionRef
	19, // 1: proto.DirectiveArchive.definition:type_name -> proto.BuildDefinitionRef
	18, // 2: proto.DirectiveList.items:type_name -> proto.Directive
	19, // 3: proto.DirectiveKernel.kernel:type_name -> proto.BuildDefinitionRef
	19, // 4: proto.DirectiveKernel.initramfs:type_name -> proto.BuildDefinitionRef
	0,  // 5: proto.Directive.run_command:type_name -> proto.DirectiveRunCommand
	1,  // 6: proto.Directive.start_service_command:type_name -> proto.DirectiveStartServiceCommand
	2,  // 7: proto.Directive.run_starlark_script:type_name -> proto.DirectiveRunStarlarkScript
	3,  // 8: proto.Directive.add_file:type_name -> proto.DirectiveAddFile
	4,  // 9: proto.Directive.local_file:type_name -> proto.DirectiveLocalFile
	5,  // 10: proto.Directive.local_directory:type_name -> proto.DirectiveLocalDirectory
	6,  // 11: proto.Directive.archive:type_name -> proto.DirectiveArchive
	7,  // 12: proto.Directive.export_port:type_name -> proto.DirectiveExportPort
	8,  // 13: proto.Directive.environment:type_name -> proto.DirectiveEnvironment
	9,  // 14: proto.Directive.builtin:type_name -> proto.DirectiveBuiltin
	10, // 15: proto.Directive.list:type_name -> proto.DirectiveList
	11, // 16: proto.Directive.add_package:type_name -> proto.DirectiveAddPackage
	12, // 17: proto.Directive.interaction:type_name -> proto.DirectiveInteraction
	13, // 18: proto.Directive.default_interactive:type_name -> proto.DirectiveDefaultInteractive
	14, // 19: proto.Directive.mount_host_directory:type_name -> proto.DirectiveMountHostDirectory
	15, // 20: proto.Directive.kernel:type_name -> proto.DirectiveKernel
	16, // 21: proto.Directive.add_init_script:type_name -> proto.DirectiveAddInitScript
	17, // 22: proto.Directive.add_volume:type_name -> proto.DirectiveAddVolume
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_directive_proto_init() }
func file_directive_proto_init() {
	if File_directive_proto != nil {
		return
	}
	file_common_proto_init()
	file_directive_proto_msgTypes[18].OneofWrappers = []any{
		(*Directive_RunCommand)(nil),
		(*Directive_StartServiceCommand)(nil),
		(*Directive_RunStarlarkScript)(nil),
		(*Directive_AddFile)(nil),
		(*Directive_LocalFile)(nil),
		(*Directive_LocalDirectory)(nil),
		(*Directive_Archive)(nil),
		(*Directive_ExportPort)(nil),
		(*Directive_Environment)(nil),
		(*Directive_Builtin)(nil),
		(*Directive_List)(nil),
		(*Directive_AddPackage)(nil),
		(*Directive_Interaction)(nil),
		(*Directive_DefaultInteractive)(nil),
		(*Directive_MountHostDirectory)(nil),
		(*Directive_Kernel)(nil),
		(*Directive_AddInitScript)(nil),
		(*Directive_AddVolume)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directive_proto_rawDesc), len(file_directive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_directive_proto_goTypes,
		DependencyIndexes: file_directive_proto_depIdxs,
		MessageInfos:      file_directive_proto_msgTypes,
	}.Build()
	File_directive_proto = out.File
	file_directive_proto_goTypes = nil
	file_directive_proto_depIdxs = nil
}
